/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 */

#ifndef _ASN_CONSTANT_H
#define _ASN_CONSTANT_H

#ifdef __cplusplus
extern "C" {
#endif

#define maxE1APid (65535)
#define maxF1APid (4)
#define maxEARFCN (65535)
#define maxNRARFCN (3279165)
#define maxnoofNrCellBands (32)
#define min_val_MME_UE_S1AP_ID (0)
#define max_val_MME_UE_S1AP_ID (4294967295)
#define min_val_QCI (0)
#define max_val_QCI (255)
#define min_val_SubscriberProfileIDforRFP (1)
#define max_val_SubscriberProfileIDforRFP (256)
#define min_val_ENB_UE_X2AP_ID (0)
#define max_val_ENB_UE_X2AP_ID (4095)
#define min_val_E_UTRA_ARFCN (0)
#define max_val_E_UTRA_ARFCN (65535)
#define min_val_NGENB_CU_UE_W1AP_ID (0)
#define max_val_NGENB_CU_UE_W1AP_ID (4294967295)
#define min_val_NGENB_DU_ID (0)
#define max_val_NGENB_DU_ID (68719476735)
#define min_val_AMF_UE_NGAP_ID (0)
#define max_val_AMF_UE_NGAP_ID (1099511627775)
#define min_val_NG_RANnodeUEXnAPID (0)
#define max_val_NG_RANnodeUEXnAPID (4294967295)
#define min_val_GNB_CU_CP_UE_E1AP_ID (0)
#define max_val_GNB_CU_CP_UE_E1AP_ID (4294967295)
#define min_val_GNB_CU_UP_ID (0)
#define max_val_GNB_CU_UP_ID (68719476735)
#define min_val_GNB_CU_UE_F1AP_ID (0)
#define max_val_GNB_CU_UE_F1AP_ID (4294967295)
#define min_val_GNB_DU_ID (0)
#define max_val_GNB_DU_ID (68719476735)
#define min_val_NR_PCI (0)
#define max_val_NR_PCI (1007)
#define maxnoofLLIs (63)
#define maxnoofMeasurementsToReport (65535)
#define maxnoofMeasurements (63)
#define maxnoofRICStyles (63)
#define maxnoofControlAction (65535)
#define maxnoofUEInfo (65535)
#define maxnoofUEs (65535)
#define maxnoofReceiveAntennas (65535)
#define maxnoofUEID (65535)
#define maxnoofCSIReports (255)
#define maxnoofUEBearers (255)
#define maxnoofLogicalChannels (63)
#define maxnoofScheduledDLSlots (63)
#define maxnoofDLGrants (63)
#define maxnoofPdschSMGs (63)
#define maxnoofCsiRsPrecodingBands (63)
#define maxnoofPrecoders (255)
#define maxnoofPrecoderCoefficients (65535)


#ifdef __cplusplus
}
#endif

#endif /* _ASN_CONSTANT_H */
