/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-LLC-IEs"
 * 	found in "e2sm_llc_v1_00.asn"
 * 	`asn1c -S /home/amd/wrk/asn1c_mouse/asn1c/skeletons/ -no-gen-BER -no-gen-UPER -no-gen-OER -no-gen-XER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps`
 */

#ifndef	_CsiReport_Item_H_
#define	_CsiReport_Item_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <BIT_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* CsiReport-Item */
typedef struct CsiReport_Item {
	long	 csiReportConfigID;
	BIT_STRING_t	 csiFieldsCsiReport_Part1;
	BIT_STRING_t	*csiFieldsCsiReport_Part2;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CsiReport_Item_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CsiReport_Item_llc_v1_01;
extern asn_SEQUENCE_specifics_t asn_SPC_CsiReport_Item_specs_1_llc_v1_01;
extern asn_TYPE_member_t asn_MBR_CsiReport_Item_1_llc_v1_01[3];

#ifdef __cplusplus
}
#endif

#endif	/* _CsiReport_Item_H_ */
#include <asn_internal.h>
