/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-LLC-IEs"
 * 	found in "e2sm_llc_v1_00_modified.asn"
 * 	`asn1c -no-gen-BER -no-gen-UPER -no-gen-OER -no-gen-XER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -S /home/amd/wrk/asn1c_oai/skeletons/`
 */

#ifndef	_CsiUeIdentifier_Item_H_
#define	_CsiUeIdentifier_Item_H_


#include <asn_application.h>

/* Including external dependencies */
#include "UEID.h"
#include <NativeEnumerated.h>
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum CsiUeIdentifier_Item__channelCarryingUCI {
	CsiUeIdentifier_Item__channelCarryingUCI_pucch	= 0,
	CsiUeIdentifier_Item__channelCarryingUCI_pusch	= 1
	/*
	 * Enumeration is extensible
	 */
} e_CsiUeIdentifier_Item__channelCarryingUCI;

/* Forward declarations */
struct CsiReport_Item;

/* CsiUeIdentifier-Item */
typedef struct CsiUeIdentifier_Item {
	UEID_t	 ueID;
	long	 channelCarryingUCI;
	struct CsiUeIdentifier_Item__csiReport_List {
		A_SEQUENCE_OF(struct CsiReport_Item) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} csiReport_List;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CsiUeIdentifier_Item_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_channelCarryingUCI_3;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_CsiUeIdentifier_Item;
extern asn_SEQUENCE_specifics_t asn_SPC_CsiUeIdentifier_Item_specs_1;
extern asn_TYPE_member_t asn_MBR_CsiUeIdentifier_Item_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _CsiUeIdentifier_Item_H_ */
#include <asn_internal.h>
