/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-LLC-IEs"
 * 	found in "e2sm_llc_v1_00_modified.asn"
 * 	`asn1c -no-gen-BER -no-gen-UPER -no-gen-OER -no-gen-XER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -S /home/amd/wrk/asn1c_oai/skeletons/`
 */

#ifndef	_Dci_10_H_
#define	_Dci_10_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <NativeEnumerated.h>
#include "SpsConfigIndex.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Dci_10__useCsiRnti__activation {
	Dci_10__useCsiRnti__activation_activate	= 0,
	Dci_10__useCsiRnti__activation_deactivate	= 1
} e_Dci_10__useCsiRnti__activation;
typedef enum Dci_10__vrbToPrbMapping {
	Dci_10__vrbToPrbMapping_interleaved	= 0
	/*
	 * Enumeration is extensible
	 */
} e_Dci_10__vrbToPrbMapping;

/* Dci-10 */
typedef struct Dci_10 {
	struct Dci_10__useCsiRnti {
		SpsConfigIndex_t	*spsConfigIndex;	/* OPTIONAL */
		long	 activation;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *useCsiRnti;
	long	 freqDomainResources;
	long	 timeDomainResources;
	long	*vrbToPrbMapping;	/* OPTIONAL */
	long	 mcs;
	long	 redundancyVersion;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Dci_10_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_activation_4;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_vrbToPrbMapping_10;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_Dci_10;
extern asn_SEQUENCE_specifics_t asn_SPC_Dci_10_specs_1;
extern asn_TYPE_member_t asn_MBR_Dci_10_1[6];

#ifdef __cplusplus
}
#endif

#endif	/* _Dci_10_H_ */
#include <asn_internal.h>
