/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-LLC-IEs"
 * 	found in "e2sm_llc_v1_00_modified.asn"
 * 	`asn1c -no-gen-BER -no-gen-UPER -no-gen-OER -no-gen-XER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -S /home/amd/wrk/asn1c_oai/skeletons/`
 */

#ifndef	_Dci_11_H_
#define	_Dci_11_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <BIT_STRING.h>
#include <NativeEnumerated.h>
#include "SpsConfigIndex.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Dci_11__vrbToPrbMapping {
	Dci_11__vrbToPrbMapping_interleaved	= 0
	/*
	 * Enumeration is extensible
	 */
} e_Dci_11__vrbToPrbMapping;

/* Dci-11 */
typedef struct Dci_11 {
	struct Dci_11__useCsiRnti {
		SpsConfigIndex_t	*spsConfigIndex;	/* OPTIONAL */
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *useCsiRnti;
	long	*carrierIndicator;	/* OPTIONAL */
	BIT_STRING_t	 freqDomainResources;
	long	 timeDomainResources;
	long	*vrbToPrbMapping;	/* OPTIONAL */
	long	 prbBundlingSizeIndicagor;
	long	 mcs_TB1;
	long	 redundancyVersion_TB1;
	long	*mcs_TB2;	/* OPTIONAL */
	long	*redundancyVersion_TB2;	/* OPTIONAL */
	BIT_STRING_t	 antennaPorts;
	long	*transmissionConfigIndication;	/* OPTIONAL */
	BIT_STRING_t	*srsRequest;	/* OPTIONAL */
	long	 dmrsSequenceInit;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Dci_11_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_vrbToPrbMapping_8;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_Dci_11;
extern asn_SEQUENCE_specifics_t asn_SPC_Dci_11_specs_1;
extern asn_TYPE_member_t asn_MBR_Dci_11_1[14];

#ifdef __cplusplus
}
#endif

#endif	/* _Dci_11_H_ */
#include <asn_internal.h>
