/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-LLC-IEs"
 * 	found in "e2sm_llc_v1_00.asn"
 * 	`asn1c -S /home/amd/wrk/asn1c_mouse/asn1c/skeletons/ -no-gen-BER -no-gen-UPER -no-gen-OER -no-gen-XER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps`
 */

#ifndef	_DlGrantOutcome_Item_H_
#define	_DlGrantOutcome_Item_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <NULL.h>
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum DlGrantOutcome_Item__executionLevel_PR {
	DlGrantOutcome_Item__executionLevel_PR_NOTHING,	/* No components present */
	DlGrantOutcome_Item__executionLevel_PR_fullyExecuted,
	DlGrantOutcome_Item__executionLevel_PR_notFullyExecuted
	/* Extensions may appear below */
	
} DlGrantOutcome_Item__executionLevel_PR;

/* Forward declarations */
struct ScheduledLogicalChannelOutcome_Item;

/* DlGrantOutcome-Item */
typedef struct DlGrantOutcome_Item {
	long	 grantID;
	struct DlGrantOutcome_Item__executionLevel {
		DlGrantOutcome_Item__executionLevel_PR present;
		union DlGrantOutcome_Item__executionLevel_u {
			NULL_t	 fullyExecuted;
			struct DlGrantOutcome_Item__executionLevel__notFullyExecuted {
				struct DlGrantOutcome_Item__executionLevel__notFullyExecuted__scheduledLogicalChannelOutcome_List {
					A_SEQUENCE_OF(struct ScheduledLogicalChannelOutcome_Item) list;
					
					/* Context for parsing across buffer boundaries */
					asn_struct_ctx_t _asn_ctx;
				} scheduledLogicalChannelOutcome_List;
				/*
				 * This type is extensible,
				 * possible extensions are below.
				 */
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} *notFullyExecuted;
			/*
			 * This type is extensible,
			 * possible extensions are below.
			 */
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} executionLevel;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DlGrantOutcome_Item_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DlGrantOutcome_Item_llc_v1_01;
extern asn_SEQUENCE_specifics_t asn_SPC_DlGrantOutcome_Item_specs_1_llc_v1_01;
extern asn_TYPE_member_t asn_MBR_DlGrantOutcome_Item_1_llc_v1_01[2];

#ifdef __cplusplus
}
#endif

#endif	/* _DlGrantOutcome_Item_H_ */
#include <asn_internal.h>
