/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-LLC-IEs"
 * 	found in "e2sm_llc_v1_00_modified.asn"
 * 	`asn1c -no-gen-BER -no-gen-UPER -no-gen-OER -no-gen-XER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -S /home/amd/wrk/asn1c_oai/skeletons/`
 */

#ifndef	_DlGrant_Item_H_
#define	_DlGrant_Item_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include "UEID.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <NULL.h>
#include <constr_CHOICE.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum DlGrant_Item__dlControlInfoType_PR {
	DlGrant_Item__dlControlInfoType_PR_NOTHING,	/* No components present */
	DlGrant_Item__dlControlInfoType_PR_dci_10,
	DlGrant_Item__dlControlInfoType_PR_dci_11,
	DlGrant_Item__dlControlInfoType_PR_semiPersistence
	/* Extensions may appear below */
	
} DlGrant_Item__dlControlInfoType_PR;

/* Forward declarations */
struct LogicalChannel_Item;
struct Dci_10;
struct Dci_11;

/* DlGrant-Item */
typedef struct DlGrant_Item {
	long	 grantID;
	long	*bwpID;	/* OPTIONAL */
	UEID_t	 ueID;
	struct DlGrant_Item__logicalChannel_List {
		A_SEQUENCE_OF(struct LogicalChannel_Item) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} logicalChannel_List;
	struct DlGrant_Item__dlControlInfoType {
		DlGrant_Item__dlControlInfoType_PR present;
		union DlGrant_Item__dlControlInfoType_u {
			struct Dci_10	*dci_10;
			struct Dci_11	*dci_11;
			NULL_t	 semiPersistence;
			/*
			 * This type is extensible,
			 * possible extensions are below.
			 */
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} dlControlInfoType;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DlGrant_Item_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DlGrant_Item;
extern asn_SEQUENCE_specifics_t asn_SPC_DlGrant_Item_specs_1;
extern asn_TYPE_member_t asn_MBR_DlGrant_Item_1[5];

#ifdef __cplusplus
}
#endif

#endif	/* _DlGrant_Item_H_ */
#include <asn_internal.h>
