/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-LLC-IEs"
 * 	found in "e2sm_llc_v1_00_modified.asn"
 * 	`asn1c -no-gen-BER -no-gen-UPER -no-gen-OER -no-gen-XER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -S /home/amd/wrk/asn1c_oai/skeletons/`
 */

#ifndef	_DlHarqUeIdentifier_Item_H_
#define	_DlHarqUeIdentifier_Item_H_


#include <asn_application.h>

/* Including external dependencies */
#include "UEID.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct DlHarqCodeword_Item;

/* DlHarqUeIdentifier-Item */
typedef struct DlHarqUeIdentifier_Item {
	UEID_t	 harqUeID;
	struct DlHarqUeIdentifier_Item__dlHarqCodeword_List {
		A_SEQUENCE_OF(struct DlHarqCodeword_Item) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} dlHarqCodeword_List;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DlHarqUeIdentifier_Item_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DlHarqUeIdentifier_Item;
extern asn_SEQUENCE_specifics_t asn_SPC_DlHarqUeIdentifier_Item_specs_1;
extern asn_TYPE_member_t asn_MBR_DlHarqUeIdentifier_Item_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _DlHarqUeIdentifier_Item_H_ */
#include <asn_internal.h>
