/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-LLC-IEs"
 * 	found in "e2sm_llc_v1_00_modified.asn"
 * 	`asn1c -no-gen-BER -no-gen-UPER -no-gen-OER -no-gen-XER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -S /home/amd/wrk/asn1c_oai/skeletons/`
 */

#ifndef	_DlRlcBufferStatus_H_
#define	_DlRlcBufferStatus_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct DlRlcUeIdentifiers_Item;

/* DlRlcBufferStatus */
typedef struct DlRlcBufferStatus {
	struct DlRlcBufferStatus__dlRlcUeIdentifiers_List {
		A_SEQUENCE_OF(struct DlRlcUeIdentifiers_Item) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} dlRlcUeIdentifiers_List;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DlRlcBufferStatus_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DlRlcBufferStatus;
extern asn_SEQUENCE_specifics_t asn_SPC_DlRlcBufferStatus_specs_1;
extern asn_TYPE_member_t asn_MBR_DlRlcBufferStatus_1[1];

#ifdef __cplusplus
}
#endif

#endif	/* _DlRlcBufferStatus_H_ */
#include <asn_internal.h>
