/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-LLC-IEs"
 * 	found in "e2sm_llc_v1_00.asn"
 * 	`asn1c -S /home/amd/wrk/asn1c_mouse/asn1c/skeletons/ -no-gen-BER -no-gen-UPER -no-gen-OER -no-gen-XER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps`
 */

#ifndef	_DlScheduledSlotOutcome_Item_H_
#define	_DlScheduledSlotOutcome_Item_H_


#include <asn_application.h>

/* Including external dependencies */
#include "SlotInfo.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct DlGrantOutcome_Item;
struct AdditionalDlAllocation_Item;
struct CsiRsPrecodingBandsNotExecuted_Item;

/* DlScheduledSlotOutcome-Item */
typedef struct DlScheduledSlotOutcome_Item {
	SlotInfo_t	 slotInfo;
	struct DlScheduledSlotOutcome_Item__dlGrantOutome_List {
		A_SEQUENCE_OF(struct DlGrantOutcome_Item) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} dlGrantOutome_List;
	struct DlScheduledSlotOutcome_Item__additionalDlAllocation_List {
		A_SEQUENCE_OF(struct AdditionalDlAllocation_Item) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} additionalDlAllocation_List;
	struct DlScheduledSlotOutcome_Item__csiRsPrecodingBandsNotExecuted_List {
		A_SEQUENCE_OF(struct CsiRsPrecodingBandsNotExecuted_Item) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} csiRsPrecodingBandsNotExecuted_List;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DlScheduledSlotOutcome_Item_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DlScheduledSlotOutcome_Item_llc_v1_01;
extern asn_SEQUENCE_specifics_t asn_SPC_DlScheduledSlotOutcome_Item_specs_1_llc_v1_01;
extern asn_TYPE_member_t asn_MBR_DlScheduledSlotOutcome_Item_1_llc_v1_01[4];

#ifdef __cplusplus
}
#endif

#endif	/* _DlScheduledSlotOutcome_Item_H_ */
#include <asn_internal.h>
