/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-LLC-IEs"
 * 	found in "e2sm_llc_v1_00_modified.asn"
 * 	`asn1c -no-gen-BER -no-gen-UPER -no-gen-OER -no-gen-XER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -S /home/amd/wrk/asn1c_oai/skeletons/`
 */

#ifndef	_DlSlotToBeScheduled_Item_H_
#define	_DlSlotToBeScheduled_Item_H_


#include <asn_application.h>

/* Including external dependencies */
#include "SlotInfo.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct DlGrant_Item;
struct PdschSMG_Item;
struct CsiRsPrecodingBand_Item;
struct Precoder_Item;

/* DlSlotToBeScheduled-Item */
typedef struct DlSlotToBeScheduled_Item {
	SlotInfo_t	 slotInfo;
	struct DlSlotToBeScheduled_Item__dlGrant_List {
		A_SEQUENCE_OF(struct DlGrant_Item) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} dlGrant_List;
	struct DlSlotToBeScheduled_Item__pdschSMG_List {
		A_SEQUENCE_OF(struct PdschSMG_Item) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} pdschSMG_List;
	struct DlSlotToBeScheduled_Item__csiRsPrecodingBand_List {
		A_SEQUENCE_OF(struct CsiRsPrecodingBand_Item) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} csiRsPrecodingBand_List;
	struct DlSlotToBeScheduled_Item__precoder_List {
		A_SEQUENCE_OF(struct Precoder_Item) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} precoder_List;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DlSlotToBeScheduled_Item_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DlSlotToBeScheduled_Item;
extern asn_SEQUENCE_specifics_t asn_SPC_DlSlotToBeScheduled_Item_specs_1;
extern asn_TYPE_member_t asn_MBR_DlSlotToBeScheduled_Item_1[5];

#ifdef __cplusplus
}
#endif

#endif	/* _DlSlotToBeScheduled_Item_H_ */
#include <asn_internal.h>
