/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-LLC-IEs"
 * 	found in "e2sm_llc_v1_00.asn"
 * 	`asn1c -S /home/amd/wrk/asn1c_mouse/asn1c/skeletons/ -no-gen-BER -no-gen-UPER -no-gen-OER -no-gen-XER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps`
 */

#ifndef	_E2SM_LLC_RANFunctionDefinition_H_
#define	_E2SM_LLC_RANFunctionDefinition_H_


#include <asn_application.h>

/* Including external dependencies */
#include "RANfunction-Name.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct RANFunctionDefinition_EventTrigger;
struct RANFunctionDefinition_Report;
struct RANFunctionDefinition_Control;

/* E2SM-LLC-RANFunctionDefinition */
typedef struct E2SM_LLC_RANFunctionDefinition {
	RANfunction_Name_t	 ranFunction_Name;
	struct RANFunctionDefinition_EventTrigger	*ranFunctionDefinition_EventTrigger;	/* OPTIONAL */
	struct RANFunctionDefinition_Report	*ranFunctionDefinition_Report;	/* OPTIONAL */
	struct RANFunctionDefinition_Control	*ranFunctionDefinition_Control;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} E2SM_LLC_RANFunctionDefinition_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_E2SM_LLC_RANFunctionDefinition_llc_v1_01;

#ifdef __cplusplus
}
#endif

#endif	/* _E2SM_LLC_RANFunctionDefinition_H_ */
#include <asn_internal.h>
