/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-LLC-IEs"
 * 	found in "e2sm_llc_v1_00_modified.asn"
 * 	`asn1c -no-gen-BER -no-gen-UPER -no-gen-OER -no-gen-XER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -S /home/amd/wrk/asn1c_oai/skeletons/`
 */

#ifndef	_E2SM_LLC_ControlHeader_Format1_H_
#define	_E2SM_LLC_ControlHeader_Format1_H_


#include <asn_application.h>

/* Including external dependencies */
#include "RIC-Style-Type.h"
#include "RIC-ControlAction-ID-llc-v1-01.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* E2SM-LLC-ControlHeader-Format1 */
typedef struct E2SM_LLC_ControlHeader_Format1 {
	RIC_Style_Type_t	 ric_StyleType;
	RIC_ControlAction_ID_llc_v1_01_t	 ric_ControlAction_ID;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} E2SM_LLC_ControlHeader_Format1_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_E2SM_LLC_ControlHeader_Format1;
extern asn_SEQUENCE_specifics_t asn_SPC_E2SM_LLC_ControlHeader_Format1_specs_1;
extern asn_TYPE_member_t asn_MBR_E2SM_LLC_ControlHeader_Format1_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _E2SM_LLC_ControlHeader_Format1_H_ */
#include <asn_internal.h>
