/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-LLC-IEs"
 * 	found in "e2sm_llc_v1_00.asn"
 * 	`asn1c -S /home/amd/wrk/asn1c_mouse/asn1c/skeletons/ -no-gen-BER -no-gen-UPER -no-gen-OER -no-gen-XER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps`
 */

#ifndef	_E2SM_LLC_EventTrigger_Format1_Item_H_
#define	_E2SM_LLC_EventTrigger_Format1_Item_H_


#include <asn_application.h>

/* Including external dependencies */
#include "RIC-EventTriggerCondition-ID.h"
#include "LowerLayers-Info-Type.h"
#include "LogicalOR.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct EventTrigger_UE_Info;

/* E2SM-LLC-EventTrigger-Format1-Item */
typedef struct E2SM_LLC_EventTrigger_Format1_Item {
	RIC_EventTriggerCondition_ID_t	 ric_eventTriggerCondition_ID;
	LowerLayers_Info_Type_t	 lowerLayersInfoType;
	struct EventTrigger_UE_Info	*associatedUEInfo;	/* OPTIONAL */
	LogicalOR_t	*logicalOR;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} E2SM_LLC_EventTrigger_Format1_Item_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_E2SM_LLC_EventTrigger_llc_v1_01_Format1_Item;
extern asn_SEQUENCE_specifics_t asn_SPC_E2SM_LLC_EventTrigger_Format1_Item_specs_1_llc_v1_01;
extern asn_TYPE_member_t asn_MBR_E2SM_LLC_EventTrigger_Format1_Item_1_llc_v1_01[4];

#ifdef __cplusplus
}
#endif

#endif	/* _E2SM_LLC_EventTrigger_Format1_Item_H_ */
#include <asn_internal.h>
