/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-LLC-IEs"
 * 	found in "e2sm_llc_v1_00.asn"
 * 	`asn1c -S /home/amd/wrk/asn1c_mouse/asn1c/skeletons/ -no-gen-BER -no-gen-UPER -no-gen-OER -no-gen-XER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps`
 */

#ifndef	_E2SM_LLC_IndicationMessage_Format1_H_
#define	_E2SM_LLC_IndicationMessage_Format1_H_


#include <asn_application.h>

/* Including external dependencies */
#include "SlotTimeStamp.h"
#include <constr_CHOICE.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum E2SM_LLC_IndicationMessage_Format1__lowerLayersInfoType_PR {
	E2SM_LLC_IndicationMessage_Format1__lowerLayersInfoType_PR_NOTHING,	/* No components present */
	E2SM_LLC_IndicationMessage_Format1__lowerLayersInfoType_PR_sRS,
	E2SM_LLC_IndicationMessage_Format1__lowerLayersInfoType_PR_cSI
	/* Extensions may appear below */
	
} E2SM_LLC_IndicationMessage_Format1__lowerLayersInfoType_PR;

/* Forward declarations */
struct SRS;
struct CSI;

/* E2SM-LLC-IndicationMessage-Format1 */
typedef struct E2SM_LLC_IndicationMessage_Format1 {
	SlotTimeStamp_t	 slotTimeStamp;
	struct E2SM_LLC_IndicationMessage_Format1__lowerLayersInfoType {
		E2SM_LLC_IndicationMessage_Format1__lowerLayersInfoType_PR present;
		union E2SM_LLC_IndicationMessage_Format1__lowerLayersInfoType_u {
			struct SRS	*sRS;
			struct CSI	*cSI;
			/*
			 * This type is extensible,
			 * possible extensions are below.
			 */
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} lowerLayersInfoType;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} E2SM_LLC_IndicationMessage_Format1_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_E2SM_LLC_IndicationMessage_llc_v1_01_Format1;
extern asn_SEQUENCE_specifics_t asn_SPC_E2SM_LLC_IndicationMessage_Format1_specs_1_llc_v1_01;
extern asn_TYPE_member_t asn_MBR_E2SM_LLC_IndicationMessage_Format1_1_llc_v1_01[2];

#ifdef __cplusplus
}
#endif

#endif	/* _E2SM_LLC_IndicationMessage_Format1_H_ */
#include <asn_internal.h>
