/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-LLC-IEs"
 * 	found in "e2sm_llc_v1_00_modified.asn"
 * 	`asn1c -no-gen-BER -no-gen-UPER -no-gen-OER -no-gen-XER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -S /home/amd/wrk/asn1c_oai/skeletons/`
 */

#ifndef	_E2SM_LLC_ControlOutcome_Format1_H_
#define	_E2SM_LLC_ControlOutcome_Format1_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ReceivedTimestamp.h"
#include <constr_CHOICE.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum E2SM_LLC_ControlOutcome_Format1__controlType_PR {
	E2SM_LLC_ControlOutcome_Format1__controlType_PR_NOTHING,	/* No components present */
	E2SM_LLC_ControlOutcome_Format1__controlType_PR_logicalChannelHandling,
	E2SM_LLC_ControlOutcome_Format1__controlType_PR_dlSchedulingParameters
	/* Extensions may appear below */
	
} E2SM_LLC_ControlOutcome_Format1__controlType_PR;

/* Forward declarations */
struct DlSchedulingControlOutcome;

/* E2SM-LLC-ControlOutcome-Format1 */
typedef struct E2SM_LLC_ControlOutcome_Format1 {
	struct E2SM_LLC_ControlOutcome_Format1__controlType {
		E2SM_LLC_ControlOutcome_Format1__controlType_PR present;
		union E2SM_LLC_ControlOutcome_Format1__controlType_u {
			ReceivedTimestamp_t	 logicalChannelHandling;
			struct DlSchedulingControlOutcome	*dlSchedulingParameters;
			/*
			 * This type is extensible,
			 * possible extensions are below.
			 */
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} controlType;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} E2SM_LLC_ControlOutcome_Format1_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_E2SM_LLC_ControlOutcome_Format1;
extern asn_SEQUENCE_specifics_t asn_SPC_E2SM_LLC_ControlOutcome_Format1_specs_1;
extern asn_TYPE_member_t asn_MBR_E2SM_LLC_ControlOutcome_Format1_1[1];

#ifdef __cplusplus
}
#endif

#endif	/* _E2SM_LLC_ControlOutcome_Format1_H_ */
#include <asn_internal.h>
