/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-LLC-IEs"
 * 	found in "e2sm_llc_v1_00_modified.asn"
 * 	`asn1c -no-gen-BER -no-gen-UPER -no-gen-OER -no-gen-XER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -S /home/amd/wrk/asn1c_oai/skeletons/`
 */

#ifndef	_EventTrigger_UE_Info_llc_v1_01_H_
#define	_EventTrigger_UE_Info_llc_v1_01_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct EventTrigger_UE_Info_Item_llc_v1_01;

/* EventTrigger-UE-Info-llc-v1-01 */
typedef struct EventTrigger_UE_Info_llc_v1_01 {
	struct EventTrigger_UE_Info_llc_v1_01__ueInfo_List {
		A_SEQUENCE_OF(struct EventTrigger_UE_Info_Item_llc_v1_01) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} ueInfo_List;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} EventTrigger_UE_Info_llc_v1_01_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_EventTrigger_UE_Info_llc_v1_01;
extern asn_SEQUENCE_specifics_t asn_SPC_EventTrigger_UE_Info_llc_v1_01_specs_1;
extern asn_TYPE_member_t asn_MBR_EventTrigger_UE_Info_llc_v1_01_1[1];

#ifdef __cplusplus
}
#endif

#endif	/* _EventTrigger_UE_Info_llc_v1_01_H_ */
#include <asn_internal.h>
