/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-LLC-IEs"
 * 	found in "e2sm_llc_v1_00.asn"
 * 	`asn1c -S /home/amd/wrk/asn1c_mouse/asn1c/skeletons/ -no-gen-BER -no-gen-UPER -no-gen-OER -no-gen-XER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps`
 */

#ifndef	_GroupOfUEs_H_
#define	_GroupOfUEs_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct CGI;
struct UeIdentifier_Item;

/* GroupOfUEs */
typedef struct GroupOfUEs {
	struct CGI	*cellGlobalID;	/* OPTIONAL */
	struct GroupOfUEs__ueIdentifier_List {
		A_SEQUENCE_OF(struct UeIdentifier_Item) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} ueIdentifier_List;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} GroupOfUEs_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_GroupOfUEs_llc_v1_01;
extern asn_SEQUENCE_specifics_t asn_SPC_GroupOfUEs_specs_1_llc_v1_01;
extern asn_TYPE_member_t asn_MBR_GroupOfUEs_1_llc_v1_01[2];

#ifdef __cplusplus
}
#endif

#endif	/* _GroupOfUEs_H_ */
#include <asn_internal.h>
