/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-COMMON-IEs"
 * 	found in "e2sm_llc_v1_00.asn"
 * 	`asn1c -S /home/amd/wrk/asn1c_mouse/asn1c/skeletons/ -no-gen-BER -no-gen-UPER -no-gen-OER -no-gen-XER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps`
 */

#ifndef	_IndexToRFSP_H_
#define	_IndexToRFSP_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* IndexToRFSP */
typedef long	 IndexToRFSP_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_IndexToRFSP_llc_v1_01;
asn_struct_free_f IndexToRFSP_free;
asn_struct_print_f IndexToRFSP_print;
asn_constr_check_f IndexToRFSP_constraint_llc_v1_01;
jer_type_encoder_f IndexToRFSP_encode_jer;
per_type_decoder_f IndexToRFSP_decode_aper;
per_type_encoder_f IndexToRFSP_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _IndexToRFSP_H_ */
#include <asn_internal.h>
