/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-LLC-IEs"
 * 	found in "e2sm_llc_v1_00_modified.asn"
 * 	`asn1c -no-gen-BER -no-gen-UPER -no-gen-OER -no-gen-XER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -S /home/amd/wrk/asn1c_oai/skeletons/`
 */

#ifndef	_LogicalChannel_Item_H_
#define	_LogicalChannel_Item_H_


#include <asn_application.h>

/* Including external dependencies */
#include "LogicalChannelID.h"
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* LogicalChannel-Item */
typedef struct LogicalChannel_Item {
	LogicalChannelID_t	 logicalChannelID;
	long	 noofBytes_TB1;
	long	*noofBytes_TB2;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LogicalChannel_Item_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LogicalChannel_Item;
extern asn_SEQUENCE_specifics_t asn_SPC_LogicalChannel_Item_specs_1;
extern asn_TYPE_member_t asn_MBR_LogicalChannel_Item_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _LogicalChannel_Item_H_ */
#include <asn_internal.h>
