/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-LLC-IEs"
 * 	found in "e2sm_llc_v1_00.asn"
 * 	`asn1c -S /home/amd/wrk/asn1c_mouse/asn1c/skeletons/ -no-gen-BER -no-gen-UPER -no-gen-OER -no-gen-XER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps`
 */

#ifndef	_LogicalChannelID_H_
#define	_LogicalChannelID_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* LogicalChannelID */
typedef long	 LogicalChannelID_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_LogicalChannelID_constr_1_llc_v1_01;
extern asn_TYPE_descriptor_t asn_DEF_LogicalChannelID_llc_v1_01;
asn_struct_free_f LogicalChannelID_free;
asn_struct_print_f LogicalChannelID_print;
asn_constr_check_f LogicalChannelID_constraint_llc_v1_01;
jer_type_encoder_f LogicalChannelID_encode_jer;
per_type_decoder_f LogicalChannelID_decode_aper;
per_type_encoder_f LogicalChannelID_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _LogicalChannelID_H_ */
#include <asn_internal.h>
