/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-LLC-IEs"
 * 	found in "e2sm_llc_v1_00.asn"
 * 	`asn1c -S /home/amd/wrk/asn1c_mouse/asn1c/skeletons/ -no-gen-BER -no-gen-UPER -no-gen-OER -no-gen-XER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps`
 */

#ifndef	_LogicalOR_H_
#define	_LogicalOR_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum LogicalOR {
	LogicalOR_true	= 0,
	LogicalOR_false	= 1
	/*
	 * Enumeration is extensible
	 */
} e_LogicalOR;

/* LogicalOR */
typedef long	 LogicalOR_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_LogicalOR_constr_1_llc_v1_01;
extern asn_TYPE_descriptor_t asn_DEF_LogicalOR_llc_v1_01;
extern const asn_INTEGER_specifics_t asn_SPC_LogicalOR_specs_1_llc_v1_01;
asn_struct_free_f LogicalOR_free;
asn_struct_print_f LogicalOR_print;
asn_constr_check_f LogicalOR_constraint;
jer_type_encoder_f LogicalOR_encode_jer;
per_type_decoder_f LogicalOR_decode_aper;
per_type_encoder_f LogicalOR_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _LogicalOR_H_ */
#include <asn_internal.h>
