/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-LLC-IEs"
 * 	found in "e2sm_llc_v1_00.asn"
 * 	`asn1c -S /home/amd/wrk/asn1c_mouse/asn1c/skeletons/ -no-gen-BER -no-gen-UPER -no-gen-OER -no-gen-XER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps`
 */

#ifndef	_LowerLayers_Meas_Type_H_
#define	_LowerLayers_Meas_Type_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum LowerLayers_Meas_Type {
	LowerLayers_Meas_Type_dl_rlc_buffer_status	= 0,
	LowerLayers_Meas_Type_dl_pdcp_buffer_status	= 1,
	LowerLayers_Meas_Type_dl_harq_statistics	= 2,
	LowerLayers_Meas_Type_slot_time_stamp	= 3
	/*
	 * Enumeration is extensible
	 */
} e_LowerLayers_Meas_Type;

/* LowerLayers-Meas-Type */
typedef long	 LowerLayers_Meas_Type_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_LowerLayers_Meas_Type_constr_1_llc_v1_01;
extern asn_TYPE_descriptor_t asn_DEF_LowerLayers_Meas_Type_llc_v1_01;
extern const asn_INTEGER_specifics_t asn_SPC_LowerLayers_Meas_Type_specs_1_llc_v1_01;
asn_struct_free_f LowerLayers_Meas_Type_free;
asn_struct_print_f LowerLayers_Meas_Type_print;
asn_constr_check_f LowerLayers_Meas_Type_constraint;
jer_type_encoder_f LowerLayers_Meas_Type_encode_jer;
per_type_decoder_f LowerLayers_Meas_Type_decode_aper;
per_type_encoder_f LowerLayers_Meas_Type_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _LowerLayers_Meas_Type_H_ */
#include <asn_internal.h>
