/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-LLC-IEs"
 * 	found in "e2sm_llc_v1_00_modified.asn"
 * 	`asn1c -no-gen-BER -no-gen-UPER -no-gen-OER -no-gen-XER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -S /home/amd/wrk/asn1c_oai/skeletons/`
 */

#ifndef	_LowerLayersMeasurement_Item_H_
#define	_LowerLayersMeasurement_Item_H_


#include <asn_application.h>

/* Including external dependencies */
#include "SlotTimeStamp.h"
#include <NULL.h>
#include <constr_CHOICE.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum LowerLayersMeasurement_Item__lowerLayersMeasurementType_PR {
	LowerLayersMeasurement_Item__lowerLayersMeasurementType_PR_NOTHING,	/* No components present */
	LowerLayersMeasurement_Item__lowerLayersMeasurementType_PR_dlRlcBufferStatus,
	LowerLayersMeasurement_Item__lowerLayersMeasurementType_PR_dlPdcpBufferStatus,
	LowerLayersMeasurement_Item__lowerLayersMeasurementType_PR_dlHarqStatistics,
	LowerLayersMeasurement_Item__lowerLayersMeasurementType_PR_slotTimeStamp
	/* Extensions may appear below */
	
} LowerLayersMeasurement_Item__lowerLayersMeasurementType_PR;

/* Forward declarations */
struct DlRlcBufferStatus;
struct DlPdcpBufferStatus;
struct DlHarqStatistics;

/* LowerLayersMeasurement-Item */
typedef struct LowerLayersMeasurement_Item {
	SlotTimeStamp_t	 slotTimeStamp;
	struct LowerLayersMeasurement_Item__lowerLayersMeasurementType {
		LowerLayersMeasurement_Item__lowerLayersMeasurementType_PR present;
		union LowerLayersMeasurement_Item__lowerLayersMeasurementType_u {
			struct DlRlcBufferStatus	*dlRlcBufferStatus;
			struct DlPdcpBufferStatus	*dlPdcpBufferStatus;
			struct DlHarqStatistics	*dlHarqStatistics;
			NULL_t	 slotTimeStamp;
			/*
			 * This type is extensible,
			 * possible extensions are below.
			 */
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} lowerLayersMeasurementType;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LowerLayersMeasurement_Item_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LowerLayersMeasurement_Item;
extern asn_SEQUENCE_specifics_t asn_SPC_LowerLayersMeasurement_Item_specs_1;
extern asn_TYPE_member_t asn_MBR_LowerLayersMeasurement_Item_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _LowerLayersMeasurement_Item_H_ */
#include <asn_internal.h>
