/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-LLC-IEs"
 * 	found in "e2sm_llc_v1_00_modified.asn"
 * 	`asn1c -no-gen-BER -no-gen-UPER -no-gen-OER -no-gen-XER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -S /home/amd/wrk/asn1c_oai/skeletons/`
 */

#ifndef	_PdschSMG_Item_H_
#define	_PdschSMG_Item_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* PdschSMG-Item */
typedef struct PdschSMG_Item {
	long	 precoderID;
	long	*smgProirity;	/* OPTIONAL */
	long	 startRB;
	long	 noofRBs;
	long	 startSymbol;
	long	 noofSymbols;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PdschSMG_Item_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PdschSMG_Item;
extern asn_SEQUENCE_specifics_t asn_SPC_PdschSMG_Item_specs_1;
extern asn_TYPE_member_t asn_MBR_PdschSMG_Item_1[6];

#ifdef __cplusplus
}
#endif

#endif	/* _PdschSMG_Item_H_ */
#include <asn_internal.h>
