/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-LLC-IEs"
 * 	found in "e2sm_llc_v1_00_modified.asn"
 * 	`asn1c -no-gen-BER -no-gen-UPER -no-gen-OER -no-gen-XER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -S /home/amd/wrk/asn1c_oai/skeletons/`
 */

#ifndef	_PrecoderCoeff_Item_H_
#define	_PrecoderCoeff_Item_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* PrecoderCoeff-Item */
typedef struct PrecoderCoeff_Item {
	long	 precoderCoeff_I;
	long	 precoderCoeff_Q;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PrecoderCoeff_Item_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PrecoderCoeff_Item;
extern asn_SEQUENCE_specifics_t asn_SPC_PrecoderCoeff_Item_specs_1;
extern asn_TYPE_member_t asn_MBR_PrecoderCoeff_Item_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _PrecoderCoeff_Item_H_ */
#include <asn_internal.h>
