/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-LLC-IEs"
 * 	found in "e2sm_llc_v1_00.asn"
 * 	`asn1c -S /home/amd/wrk/asn1c_mouse/asn1c/skeletons/ -no-gen-BER -no-gen-UPER -no-gen-OER -no-gen-XER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps`
 */

#ifndef	_Precoder_Item_H_
#define	_Precoder_Item_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>
#include <constr_SEQUENCE.h>
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct PrecoderCoeff_Item;

/* Precoder-Item */
typedef struct Precoder_Item {
	struct Precoder_Item__compressionInformation {
		OCTET_STRING_t	 precoderCompressionHeader;
		OCTET_STRING_t	 precoderCompressionParam;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *compressionInformation;
	struct Precoder_Item__precoderCoeff_List {
		A_SEQUENCE_OF(struct PrecoderCoeff_Item) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} precoderCoeff_List;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Precoder_Item_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Precoder_Item_llc_v1_01;
extern asn_SEQUENCE_specifics_t asn_SPC_Precoder_Item_specs_1_llc_v1_01;
extern asn_TYPE_member_t asn_MBR_Precoder_Item_1_llc_v1_01[2];

#ifdef __cplusplus
}
#endif

#endif	/* _Precoder_Item_H_ */
#include <asn_internal.h>
