/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-LLC-IEs"
 * 	found in "e2sm_llc_v1_00.asn"
 * 	`asn1c -S /home/amd/wrk/asn1c_mouse/asn1c/skeletons/ -no-gen-BER -no-gen-UPER -no-gen-OER -no-gen-XER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps`
 */

#ifndef	_RANFunctionDefinition_Control_Item_H_
#define	_RANFunctionDefinition_Control_Item_H_


#include <asn_application.h>

/* Including external dependencies */
#include "RIC-Style-Type.h"
#include "RIC-Style-Name.h"
#include "RIC-Format-Type.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct RANFunctionDefinition_Control_Action_Item;

/* RANFunctionDefinition-Control-Item */
typedef struct RANFunctionDefinition_Control_Item {
	RIC_Style_Type_t	 ric_ControlStyle_Type;
	RIC_Style_Name_t	 ric_ControlStyle_Name;
	struct RANFunctionDefinition_Control_Item__ric_ControlAction_List {
		A_SEQUENCE_OF(struct RANFunctionDefinition_Control_Action_Item) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *ric_ControlAction_List;
	RIC_Format_Type_t	 ric_ControlHeaderFormat_Type;
	RIC_Format_Type_t	 ric_ControlMessageFormat_Type;
	RIC_Format_Type_t	*ric_CallProcessIDFormat_Type;	/* OPTIONAL */
	RIC_Format_Type_t	 ric_ControlOutcomeFormat_Type;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RANFunctionDefinition_Control_Item_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RANFunctionDefinition_Control_llc_v1_01_Item;
extern asn_SEQUENCE_specifics_t asn_SPC_RANFunctionDefinition_Control_Item_specs_1_llc_v1_01;
extern asn_TYPE_member_t asn_MBR_RANFunctionDefinition_Control_Item_1_llc_v1_01[7];

#ifdef __cplusplus
}
#endif

#endif	/* _RANFunctionDefinition_Control_Item_H_ */
#include <asn_internal.h>
