/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-LLC-IEs"
 * 	found in "e2sm_llc_v1_00_modified.asn"
 * 	`asn1c -no-gen-BER -no-gen-UPER -no-gen-OER -no-gen-XER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -S /home/amd/wrk/asn1c_oai/skeletons/`
 */

#ifndef	_RANFunctionDefinition_Control_Action_Item_llc_v1_01_H_
#define	_RANFunctionDefinition_Control_Action_Item_llc_v1_01_H_


#include <asn_application.h>

/* Including external dependencies */
#include "RIC-ControlAction-ID-llc-v1-01.h"
#include "RIC-ControlAction-Name-llc-v1-01.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* RANFunctionDefinition-Control-Action-Item-llc-v1-01 */
typedef struct RANFunctionDefinition_Control_Action_Item_llc_v1_01 {
	RIC_ControlAction_ID_llc_v1_01_t	 ric_ControlAction_ID;
	RIC_ControlAction_Name_llc_v1_01_t	 ric_ControlAction_Name;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RANFunctionDefinition_Control_Action_Item_llc_v1_01_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RANFunctionDefinition_Control_Action_Item_llc_v1_01;
extern asn_SEQUENCE_specifics_t asn_SPC_RANFunctionDefinition_Control_Action_Item_llc_v1_01_specs_1;
extern asn_TYPE_member_t asn_MBR_RANFunctionDefinition_Control_Action_Item_llc_v1_01_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _RANFunctionDefinition_Control_Action_Item_llc_v1_01_H_ */
#include <asn_internal.h>
