/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-LLC-IEs"
 * 	found in "e2sm_llc_v1_00_modified.asn"
 * 	`asn1c -no-gen-BER -no-gen-UPER -no-gen-OER -no-gen-XER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -S /home/amd/wrk/asn1c_oai/skeletons/`
 */

#ifndef	_SlotInfo_H_
#define	_SlotInfo_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <constr_CHOICE.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum SlotInfo__slotIndex_PR {
	SlotInfo__slotIndex_PR_NOTHING,	/* No components present */
	SlotInfo__slotIndex_PR_scs_15,
	SlotInfo__slotIndex_PR_scs_30,
	SlotInfo__slotIndex_PR_scs_60,
	SlotInfo__slotIndex_PR_scs_120
	/* Extensions may appear below */
	
} SlotInfo__slotIndex_PR;

/* SlotInfo */
typedef struct SlotInfo {
	long	 systemFramNumber;
	struct SlotInfo__slotIndex {
		SlotInfo__slotIndex_PR present;
		union SlotInfo__slotIndex_u {
			long	 scs_15;
			long	 scs_30;
			long	 scs_60;
			long	 scs_120;
			/*
			 * This type is extensible,
			 * possible extensions are below.
			 */
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} slotIndex;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SlotInfo_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SlotInfo;
extern asn_SEQUENCE_specifics_t asn_SPC_SlotInfo_specs_1;
extern asn_TYPE_member_t asn_MBR_SlotInfo_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _SlotInfo_H_ */
#include <asn_internal.h>
