/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-LLC-IEs"
 * 	found in "e2sm_llc_v1_00_modified.asn"
 * 	`asn1c -no-gen-BER -no-gen-UPER -no-gen-OER -no-gen-XER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -S /home/amd/wrk/asn1c_oai/skeletons/`
 */

#ifndef	_SlotTimeStamp_H_
#define	_SlotTimeStamp_H_


#include <asn_application.h>

/* Including external dependencies */
#include "SlotInfo.h"
#include <OCTET_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SlotTimeStamp */
typedef struct SlotTimeStamp {
	SlotInfo_t	 slotInfo;
	OCTET_STRING_t	 slotStartTime;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SlotTimeStamp_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SlotTimeStamp;
extern asn_SEQUENCE_specifics_t asn_SPC_SlotTimeStamp_specs_1;
extern asn_TYPE_member_t asn_MBR_SlotTimeStamp_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _SlotTimeStamp_H_ */
#include <asn_internal.h>
