/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-LLC-IEs"
 * 	found in "e2sm_llc_v1_00_modified.asn"
 * 	`asn1c -no-gen-BER -no-gen-UPER -no-gen-OER -no-gen-XER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -S /home/amd/wrk/asn1c_oai/skeletons/`
 */

#ifndef	_SpsConfigIndex_H_
#define	_SpsConfigIndex_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SpsConfigIndex */
typedef long	 SpsConfigIndex_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_SpsConfigIndex_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_SpsConfigIndex;
asn_struct_free_f SpsConfigIndex_free;
asn_struct_print_f SpsConfigIndex_print;
asn_constr_check_f SpsConfigIndex_constraint;
jer_type_encoder_f SpsConfigIndex_encode_jer;
per_type_decoder_f SpsConfigIndex_decode_aper;
per_type_encoder_f SpsConfigIndex_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _SpsConfigIndex_H_ */
#include <asn_internal.h>
