/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-LLC-IEs"
 * 	found in "e2sm_llc_v1_00.asn"
 * 	`asn1c -S /home/amd/wrk/asn1c_mouse/asn1c/skeletons/ -no-gen-BER -no-gen-UPER -no-gen-OER -no-gen-XER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps`
 */

#ifndef	_SrsReceiveAntenna_Item_H_
#define	_SrsReceiveAntenna_Item_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct SrsSymbol_Item;

/* SrsReceiveAntenna-Item */
typedef struct SrsReceiveAntenna_Item {
	struct SrsReceiveAntenna_Item__srsSymbol_List {
		A_SEQUENCE_OF(struct SrsSymbol_Item) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} srsSymbol_List;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SrsReceiveAntenna_Item_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SrsReceiveAntenna_Item_llc_v1_01;
extern asn_SEQUENCE_specifics_t asn_SPC_SrsReceiveAntenna_Item_specs_1_llc_v1_01;
extern asn_TYPE_member_t asn_MBR_SrsReceiveAntenna_Item_1_llc_v1_01[1];

#ifdef __cplusplus
}
#endif

#endif	/* _SrsReceiveAntenna_Item_H_ */
#include <asn_internal.h>
