/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "nr-rrc-17.3.0.asn1"
 * 	`asn1c -no-gen-BER -no-gen-OER -no-gen-XER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -S /home/amd/wrk/asn1c_oai/skeletons/`
 */

#ifndef	_AreaConfig_r16_H_
#define	_AreaConfig_r16_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum AreaConfig_r16_PR {
	AreaConfig_r16_PR_NOTHING,	/* No components present */
	AreaConfig_r16_PR_cellGlobalIdList_r16,
	AreaConfig_r16_PR_trackingAreaCodeList_r16,
	AreaConfig_r16_PR_trackingAreaIdentityList_r16
} AreaConfig_r16_PR;

/* Forward declarations */
struct CellGlobalIdList_r16;
struct TrackingAreaCodeList_r16;
struct TrackingAreaIdentityList_r16;

/* AreaConfig-r16 */
typedef struct AreaConfig_r16 {
	AreaConfig_r16_PR present;
	union AreaConfig_r16_u {
		struct CellGlobalIdList_r16	*cellGlobalIdList_r16;
		struct TrackingAreaCodeList_r16	*trackingAreaCodeList_r16;
		struct TrackingAreaIdentityList_r16	*trackingAreaIdentityList_r16;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} AreaConfig_r16_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AreaConfig_r16;
extern asn_CHOICE_specifics_t asn_SPC_AreaConfig_r16_specs_1;
extern asn_TYPE_member_t asn_MBR_AreaConfig_r16_1[3];
extern asn_per_constraints_t asn_PER_type_AreaConfig_r16_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _AreaConfig_r16_H_ */
#include <asn_internal.h>
