/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "PC5-RRC-Definitions"
 * 	found in "nr-rrc-17.3.0.asn1"
 * 	`asn1c -no-gen-BER -no-gen-OER -no-gen-XER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -S /home/amd/wrk/asn1c_oai/skeletons/`
 */

#ifndef	_BandParametersSidelink_v1710_H_
#define	_BandParametersSidelink_v1710_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum BandParametersSidelink_v1710__tx_IUC_Scheme1_Mode2Sidelink_r17 {
	BandParametersSidelink_v1710__tx_IUC_Scheme1_Mode2Sidelink_r17_supported	= 0
} e_BandParametersSidelink_v1710__tx_IUC_Scheme1_Mode2Sidelink_r17;
typedef enum BandParametersSidelink_v1710__tx_IUC_Scheme2_Mode2Sidelink_r17 {
	BandParametersSidelink_v1710__tx_IUC_Scheme2_Mode2Sidelink_r17_n4	= 0,
	BandParametersSidelink_v1710__tx_IUC_Scheme2_Mode2Sidelink_r17_n8	= 1,
	BandParametersSidelink_v1710__tx_IUC_Scheme2_Mode2Sidelink_r17_n16	= 2
} e_BandParametersSidelink_v1710__tx_IUC_Scheme2_Mode2Sidelink_r17;

/* BandParametersSidelink-v1710 */
typedef struct BandParametersSidelink_v1710 {
	long	*tx_IUC_Scheme1_Mode2Sidelink_r17;	/* OPTIONAL */
	long	*tx_IUC_Scheme2_Mode2Sidelink_r17;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} BandParametersSidelink_v1710_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_tx_IUC_Scheme1_Mode2Sidelink_r17_2;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_tx_IUC_Scheme2_Mode2Sidelink_r17_4;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_BandParametersSidelink_v1710;
extern asn_SEQUENCE_specifics_t asn_SPC_BandParametersSidelink_v1710_specs_1;
extern asn_TYPE_member_t asn_MBR_BandParametersSidelink_v1710_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _BandParametersSidelink_v1710_H_ */
#include <asn_internal.h>
