/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "nr-rrc-17.3.0.asn1"
 * 	`asn1c -no-gen-BER -no-gen-OER -no-gen-XER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -S /home/amd/wrk/asn1c_oai/skeletons/`
 */

#ifndef	_BandCombination_v1650_H_
#define	_BandCombination_v1650_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct CA_ParametersNRDC_v1650;

/* BandCombination-v1650 */
typedef struct BandCombination_v1650 {
	struct CA_ParametersNRDC_v1650	*ca_ParametersNRDC_v1650;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} BandCombination_v1650_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_BandCombination_v1650;
extern asn_SEQUENCE_specifics_t asn_SPC_BandCombination_v1650_specs_1;
extern asn_TYPE_member_t asn_MBR_BandCombination_v1650_1[1];

#ifdef __cplusplus
}
#endif

#endif	/* _BandCombination_v1650_H_ */
#include <asn_internal.h>
