/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "nr-rrc-17.3.0.asn1"
 * 	`asn1c -no-gen-BER -no-gen-OER -no-gen-XER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -S /home/amd/wrk/asn1c_oai/skeletons/`
 */

#ifndef	_BandCombination_v1680_H_
#define	_BandCombination_v1680_H_


#include <asn_application.h>

/* Including external dependencies */
#include "IntraBandPowerClass-r16.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* BandCombination-v1680 */
typedef struct BandCombination_v1680 {
	struct BandCombination_v1680__intrabandConcurrentOperationPowerClass_r16 {
		A_SEQUENCE_OF(IntraBandPowerClass_r16_t) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *intrabandConcurrentOperationPowerClass_r16;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} BandCombination_v1680_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_BandCombination_v1680;
extern asn_SEQUENCE_specifics_t asn_SPC_BandCombination_v1680_specs_1;
extern asn_TYPE_member_t asn_MBR_BandCombination_v1680_1[1];

#ifdef __cplusplus
}
#endif

#endif	/* _BandCombination_v1680_H_ */
#include <asn_internal.h>
