/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "nr-rrc-17.3.0.asn1"
 * 	`asn1c -no-gen-BER -no-gen-OER -no-gen-XER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -S /home/amd/wrk/asn1c_oai/skeletons/`
 */

#ifndef	_BWP_DownlinkCommon_H_
#define	_BWP_DownlinkCommon_H_


#include <asn_application.h>

/* Including external dependencies */
#include "BWP.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct SetupRelease_PDCCH_ConfigCommon;
struct SetupRelease_PDSCH_ConfigCommon;

/* BWP-DownlinkCommon */
typedef struct BWP_DownlinkCommon {
	BWP_t	 genericParameters;
	struct SetupRelease_PDCCH_ConfigCommon	*pdcch_ConfigCommon;	/* OPTIONAL */
	struct SetupRelease_PDSCH_ConfigCommon	*pdsch_ConfigCommon;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} BWP_DownlinkCommon_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_BWP_DownlinkCommon;
extern asn_SEQUENCE_specifics_t asn_SPC_BWP_DownlinkCommon_specs_1;
extern asn_TYPE_member_t asn_MBR_BWP_DownlinkCommon_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _BWP_DownlinkCommon_H_ */
#include <asn_internal.h>
