/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "nr-rrc-17.3.0.asn1"
 * 	`asn1c -no-gen-BER -no-gen-OER -no-gen-XER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -S /home/amd/wrk/asn1c_oai/skeletons/`
 */

#ifndef	_CA_ParametersNRDC_v1720_H_
#define	_CA_ParametersNRDC_v1720_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct CA_ParametersNR_v1700;
struct CA_ParametersNR_v1720;

/* CA-ParametersNRDC-v1720 */
typedef struct CA_ParametersNRDC_v1720 {
	struct CA_ParametersNR_v1700	*ca_ParametersNR_ForDC_v1700;	/* OPTIONAL */
	struct CA_ParametersNR_v1720	*ca_ParametersNR_ForDC_v1720;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CA_ParametersNRDC_v1720_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CA_ParametersNRDC_v1720;
extern asn_SEQUENCE_specifics_t asn_SPC_CA_ParametersNRDC_v1720_specs_1;
extern asn_TYPE_member_t asn_MBR_CA_ParametersNRDC_v1720_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _CA_ParametersNRDC_v1720_H_ */
#include <asn_internal.h>
