/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "nr-rrc-17.3.0.asn1"
 * 	`asn1c -no-gen-BER -no-gen-OER -no-gen-XER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -S /home/amd/wrk/asn1c_oai/skeletons/`
 */

#ifndef	_CarrierState_r17_H_
#define	_CarrierState_r17_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NULL.h>
#include <NativeInteger.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum CarrierState_r17_PR {
	CarrierState_r17_PR_NOTHING,	/* No components present */
	CarrierState_r17_PR_deActivated_r17,
	CarrierState_r17_PR_activeBWP_r17
} CarrierState_r17_PR;

/* CarrierState-r17 */
typedef struct CarrierState_r17 {
	CarrierState_r17_PR present;
	union CarrierState_r17_u {
		NULL_t	 deActivated_r17;
		long	 activeBWP_r17;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CarrierState_r17_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CarrierState_r17;
extern asn_CHOICE_specifics_t asn_SPC_CarrierState_r17_specs_1;
extern asn_TYPE_member_t asn_MBR_CarrierState_r17_1[2];
extern asn_per_constraints_t asn_PER_type_CarrierState_r17_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _CarrierState_r17_H_ */
#include <asn_internal.h>
