/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "nr-rrc-17.3.0.asn1"
 * 	`asn1c -no-gen-BER -no-gen-OER -no-gen-XER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -S /home/amd/wrk/asn1c_oai/skeletons/`
 */

#ifndef	_CarrierFreqListEUTRA_v1700_H_
#define	_CarrierFreqListEUTRA_v1700_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct CarrierFreqEUTRA_v1700;

/* CarrierFreqListEUTRA-v1700 */
typedef struct CarrierFreqListEUTRA_v1700 {
	A_SEQUENCE_OF(struct CarrierFreqEUTRA_v1700) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CarrierFreqListEUTRA_v1700_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CarrierFreqListEUTRA_v1700;
extern asn_SET_OF_specifics_t asn_SPC_CarrierFreqListEUTRA_v1700_specs_1;
extern asn_TYPE_member_t asn_MBR_CarrierFreqListEUTRA_v1700_1[1];
extern asn_per_constraints_t asn_PER_type_CarrierFreqListEUTRA_v1700_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _CarrierFreqListEUTRA_v1700_H_ */
#include <asn_internal.h>
