/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "nr-rrc-17.3.0.asn1"
 * 	`asn1c -no-gen-BER -no-gen-OER -no-gen-XER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -S /home/amd/wrk/asn1c_oai/skeletons/`
 */

#ifndef	_CC_Group_r17_H_
#define	_CC_Group_r17_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ServCellIndex.h"
#include "DefaultDC-Location-r17.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_CHOICE.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum CC_Group_r17__offsetToDefault_r17_PR {
	CC_Group_r17__offsetToDefault_r17_PR_NOTHING,	/* No components present */
	CC_Group_r17__offsetToDefault_r17_PR_offsetValue,
	CC_Group_r17__offsetToDefault_r17_PR_offsetlist
} CC_Group_r17__offsetToDefault_r17_PR;

/* Forward declarations */
struct OffsetValue_r17;

/* CC-Group-r17 */
typedef struct CC_Group_r17 {
	ServCellIndex_t	 servCellIndexLower_r17;
	ServCellIndex_t	*servCellIndexHigher_r17;	/* OPTIONAL */
	DefaultDC_Location_r17_t	 defaultDC_Location_r17;
	struct CC_Group_r17__offsetToDefault_r17 {
		CC_Group_r17__offsetToDefault_r17_PR present;
		union CC_Group_r17__offsetToDefault_r17_u {
			struct OffsetValue_r17	*offsetValue;
			struct CC_Group_r17__offsetToDefault_r17__offsetlist {
				A_SEQUENCE_OF(struct OffsetValue_r17) list;
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} *offsetlist;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *offsetToDefault_r17;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CC_Group_r17_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CC_Group_r17;
extern asn_SEQUENCE_specifics_t asn_SPC_CC_Group_r17_specs_1;
extern asn_TYPE_member_t asn_MBR_CC_Group_r17_1[4];

#ifdef __cplusplus
}
#endif

#endif	/* _CC_Group_r17_H_ */
#include <asn_internal.h>
