/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "nr-rrc-17.3.0.asn1"
 * 	`asn1c -no-gen-BER -no-gen-OER -no-gen-XER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -S /home/amd/wrk/asn1c_oai/skeletons/`
 */

#ifndef	_CFR_ConfigMulticast_r17_H_
#define	_CFR_ConfigMulticast_r17_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct PDCCH_Config;
struct PDSCH_Config;
struct SPS_ConfigMulticastToAddModList_r17;
struct SPS_ConfigMulticastToReleaseList_r17;

/* CFR-ConfigMulticast-r17 */
typedef struct CFR_ConfigMulticast_r17 {
	long	*locationAndBandwidthMulticast_r17;	/* OPTIONAL */
	struct PDCCH_Config	*pdcch_ConfigMulticast_r17;	/* OPTIONAL */
	struct PDSCH_Config	*pdsch_ConfigMulticast_r17;	/* OPTIONAL */
	struct SPS_ConfigMulticastToAddModList_r17	*sps_ConfigMulticastToAddModList_r17;	/* OPTIONAL */
	struct SPS_ConfigMulticastToReleaseList_r17	*sps_ConfigMulticastToReleaseList_r17;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CFR_ConfigMulticast_r17_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CFR_ConfigMulticast_r17;
extern asn_SEQUENCE_specifics_t asn_SPC_CFR_ConfigMulticast_r17_specs_1;
extern asn_TYPE_member_t asn_MBR_CFR_ConfigMulticast_r17_1[5];

#ifdef __cplusplus
}
#endif

#endif	/* _CFR_ConfigMulticast_r17_H_ */
#include <asn_internal.h>
