/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-InterNodeDefinitions"
 * 	found in "nr-rrc-17.3.0.asn1"
 * 	`asn1c -no-gen-BER -no-gen-OER -no-gen-XER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -S /home/amd/wrk/asn1c_oai/skeletons/`
 */

#ifndef	_CG_Config_v1610_IEs_H_
#define	_CG_Config_v1610_IEs_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct DRX_Info2;
struct CG_Config_v1620_IEs;

/* CG-Config-v1610-IEs */
typedef struct CG_Config_v1610_IEs {
	struct DRX_Info2	*drx_InfoSCG2;	/* OPTIONAL */
	struct CG_Config_v1620_IEs	*nonCriticalExtension;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CG_Config_v1610_IEs_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CG_Config_v1610_IEs;
extern asn_SEQUENCE_specifics_t asn_SPC_CG_Config_v1610_IEs_specs_1;
extern asn_TYPE_member_t asn_MBR_CG_Config_v1610_IEs_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _CG_Config_v1610_IEs_H_ */
#include <asn_internal.h>
