/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "nr-rrc-17.3.0.asn1"
 * 	`asn1c -no-gen-BER -no-gen-OER -no-gen-XER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -S /home/amd/wrk/asn1c_oai/skeletons/`
 */

#ifndef	_CGI_InfoNR_H_
#define	_CGI_InfoNR_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include "PDCCH-ConfigSIB1.h"
#include <constr_SEQUENCE.h>
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum CGI_InfoNR__ext2__cellReservedForOtherUse_r16 {
	CGI_InfoNR__ext2__cellReservedForOtherUse_r16_true	= 0
} e_CGI_InfoNR__ext2__cellReservedForOtherUse_r16;

/* Forward declarations */
struct PLMN_IdentityInfoList;
struct MultiFrequencyBandListNR;
struct NPN_IdentityInfoList_r16;

/* CGI-InfoNR */
typedef struct CGI_InfoNR {
	struct PLMN_IdentityInfoList	*plmn_IdentityInfoList;	/* OPTIONAL */
	struct MultiFrequencyBandListNR	*frequencyBandList;	/* OPTIONAL */
	struct CGI_InfoNR__noSIB1 {
		long	 ssb_SubcarrierOffset;
		PDCCH_ConfigSIB1_t	 pdcch_ConfigSIB1;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *noSIB1;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	struct CGI_InfoNR__ext1 {
		struct NPN_IdentityInfoList_r16	*npn_IdentityInfoList_r16;	/* OPTIONAL */
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *ext1;
	struct CGI_InfoNR__ext2 {
		long	*cellReservedForOtherUse_r16;	/* OPTIONAL */
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *ext2;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CGI_InfoNR_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_cellReservedForOtherUse_r16_11;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_CGI_InfoNR;
extern asn_SEQUENCE_specifics_t asn_SPC_CGI_InfoNR_specs_1;
extern asn_TYPE_member_t asn_MBR_CGI_InfoNR_1[5];

#ifdef __cplusplus
}
#endif

#endif	/* _CGI_InfoNR_H_ */
#include <asn_internal.h>
