/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "nr-rrc-17.3.0.asn1"
 * 	`asn1c -no-gen-BER -no-gen-OER -no-gen-XER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -S /home/amd/wrk/asn1c_oai/skeletons/`
 */

#ifndef	_ChoCandidateCell_r17_H_
#define	_ChoCandidateCell_r17_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ChoCandidateCell_r17_PR {
	ChoCandidateCell_r17_PR_NOTHING,	/* No components present */
	ChoCandidateCell_r17_PR_cellGlobalId_r17,
	ChoCandidateCell_r17_PR_pci_arfcn_r17
} ChoCandidateCell_r17_PR;

/* Forward declarations */
struct CGI_Info_Logging_r16;
struct PCI_ARFCN_NR_r16;

/* ChoCandidateCell-r17 */
typedef struct ChoCandidateCell_r17 {
	ChoCandidateCell_r17_PR present;
	union ChoCandidateCell_r17_u {
		struct CGI_Info_Logging_r16	*cellGlobalId_r17;
		struct PCI_ARFCN_NR_r16	*pci_arfcn_r17;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ChoCandidateCell_r17_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ChoCandidateCell_r17;
extern asn_CHOICE_specifics_t asn_SPC_ChoCandidateCell_r17_specs_1;
extern asn_TYPE_member_t asn_MBR_ChoCandidateCell_r17_1[2];
extern asn_per_constraints_t asn_PER_type_ChoCandidateCell_r17_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _ChoCandidateCell_r17_H_ */
#include <asn_internal.h>
