/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-UE-Variables"
 * 	found in "nr-rrc-17.3.0.asn1"
 * 	`asn1c -no-gen-BER -no-gen-OER -no-gen-XER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -S /home/amd/wrk/asn1c_oai/skeletons/`
 */

#ifndef	_CLI_TriggeredList_r16_H_
#define	_CLI_TriggeredList_r16_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum CLI_TriggeredList_r16_PR {
	CLI_TriggeredList_r16_PR_NOTHING,	/* No components present */
	CLI_TriggeredList_r16_PR_srs_RSRP_TriggeredList_r16,
	CLI_TriggeredList_r16_PR_cli_RSSI_TriggeredList_r16
} CLI_TriggeredList_r16_PR;

/* Forward declarations */
struct SRS_RSRP_TriggeredList_r16;
struct CLI_RSSI_TriggeredList_r16;

/* CLI-TriggeredList-r16 */
typedef struct CLI_TriggeredList_r16 {
	CLI_TriggeredList_r16_PR present;
	union CLI_TriggeredList_r16_u {
		struct SRS_RSRP_TriggeredList_r16	*srs_RSRP_TriggeredList_r16;
		struct CLI_RSSI_TriggeredList_r16	*cli_RSSI_TriggeredList_r16;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CLI_TriggeredList_r16_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CLI_TriggeredList_r16;
extern asn_CHOICE_specifics_t asn_SPC_CLI_TriggeredList_r16_specs_1;
extern asn_TYPE_member_t asn_MBR_CLI_TriggeredList_r16_1[2];
extern asn_per_constraints_t asn_PER_type_CLI_TriggeredList_r16_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _CLI_TriggeredList_r16_H_ */
#include <asn_internal.h>
