/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-InterNodeDefinitions"
 * 	found in "nr-rrc-17.3.0.asn1"
 * 	`asn1c -no-gen-BER -no-gen-OER -no-gen-XER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -S /home/amd/wrk/asn1c_oai/skeletons/`
 */

#ifndef	_ConfigRestrictInfoDAPS_v1640_H_
#define	_ConfigRestrictInfoDAPS_v1640_H_


#include <asn_application.h>

/* Including external dependencies */
#include "FeatureSetDownlinkPerCC-Id.h"
#include "FeatureSetUplinkPerCC-Id.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ConfigRestrictInfoDAPS-v1640 */
typedef struct ConfigRestrictInfoDAPS_v1640 {
	FeatureSetDownlinkPerCC_Id_t	 sourceFeatureSetPerDownlinkCC_r16;
	FeatureSetUplinkPerCC_Id_t	 sourceFeatureSetPerUplinkCC_r16;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ConfigRestrictInfoDAPS_v1640_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ConfigRestrictInfoDAPS_v1640;
extern asn_SEQUENCE_specifics_t asn_SPC_ConfigRestrictInfoDAPS_v1640_specs_1;
extern asn_TYPE_member_t asn_MBR_ConfigRestrictInfoDAPS_v1640_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _ConfigRestrictInfoDAPS_v1640_H_ */
#include <asn_internal.h>
