/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "nr-rrc-17.3.0.asn1"
 * 	`asn1c -no-gen-BER -no-gen-OER -no-gen-XER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -S /home/amd/wrk/asn1c_oai/skeletons/`
 */

#ifndef	_DLInformationTransfer_v1700_IEs_H_
#define	_DLInformationTransfer_v1700_IEs_H_


#include <asn_application.h>

/* Including external dependencies */
#include "DedicatedInfoF1c-r17.h"
#include <NativeEnumerated.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum DLInformationTransfer_v1700_IEs__ta_PDC_r17 {
	DLInformationTransfer_v1700_IEs__ta_PDC_r17_activate	= 0,
	DLInformationTransfer_v1700_IEs__ta_PDC_r17_deactivate	= 1
} e_DLInformationTransfer_v1700_IEs__ta_PDC_r17;
typedef enum DLInformationTransfer_v1700_IEs__sib9Fallback_r17 {
	DLInformationTransfer_v1700_IEs__sib9Fallback_r17_true	= 0
} e_DLInformationTransfer_v1700_IEs__sib9Fallback_r17;

/* Forward declarations */
struct RxTxTimeDiff_r17;

/* DLInformationTransfer-v1700-IEs */
typedef struct DLInformationTransfer_v1700_IEs {
	DedicatedInfoF1c_r17_t	*dedicatedInfoF1c_r17;	/* OPTIONAL */
	struct RxTxTimeDiff_r17	*rxTxTimeDiff_gNB_r17;	/* OPTIONAL */
	long	*ta_PDC_r17;	/* OPTIONAL */
	long	*sib9Fallback_r17;	/* OPTIONAL */
	struct DLInformationTransfer_v1700_IEs__nonCriticalExtension {
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *nonCriticalExtension;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DLInformationTransfer_v1700_IEs_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_ta_PDC_r17_4;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_sib9Fallback_r17_7;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_DLInformationTransfer_v1700_IEs;
extern asn_SEQUENCE_specifics_t asn_SPC_DLInformationTransfer_v1700_IEs_specs_1;
extern asn_TYPE_member_t asn_MBR_DLInformationTransfer_v1700_IEs_1[5];

#ifdef __cplusplus
}
#endif

#endif	/* _DLInformationTransfer_v1700_IEs_H_ */
#include <asn_internal.h>
