/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "nr-rrc-17.3.0.asn1"
 * 	`asn1c -no-gen-BER -no-gen-OER -no-gen-XER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -S /home/amd/wrk/asn1c_oai/skeletons/`
 */

#ifndef	_DormantBWP_Config_r16_H_
#define	_DormantBWP_Config_r16_H_


#include <asn_application.h>

/* Including external dependencies */
#include "BWP-Id.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct SetupRelease_WithinActiveTimeConfig_r16;
struct SetupRelease_OutsideActiveTimeConfig_r16;

/* DormantBWP-Config-r16 */
typedef struct DormantBWP_Config_r16 {
	BWP_Id_t	*dormantBWP_Id_r16;	/* OPTIONAL */
	struct SetupRelease_WithinActiveTimeConfig_r16	*withinActiveTimeConfig_r16;	/* OPTIONAL */
	struct SetupRelease_OutsideActiveTimeConfig_r16	*outsideActiveTimeConfig_r16;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DormantBWP_Config_r16_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DormantBWP_Config_r16;
extern asn_SEQUENCE_specifics_t asn_SPC_DormantBWP_Config_r16_specs_1;
extern asn_TYPE_member_t asn_MBR_DormantBWP_Config_r16_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _DormantBWP_Config_r16_H_ */
#include <asn_internal.h>
