/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "nr-rrc-17.3.0.asn1"
 * 	`asn1c -no-gen-BER -no-gen-OER -no-gen-XER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -S /home/amd/wrk/asn1c_oai/skeletons/`
 */

#ifndef	_DownlinkConfigCommonSIB_H_
#define	_DownlinkConfigCommonSIB_H_


#include <asn_application.h>

/* Including external dependencies */
#include "FrequencyInfoDL-SIB.h"
#include "BWP-DownlinkCommon.h"
#include "BCCH-Config.h"
#include "PCCH-Config.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct PEI_Config_r17;
struct BWP_DownlinkCommon;

/* DownlinkConfigCommonSIB */
typedef struct DownlinkConfigCommonSIB {
	FrequencyInfoDL_SIB_t	 frequencyInfoDL;
	BWP_DownlinkCommon_t	 initialDownlinkBWP;
	BCCH_Config_t	 bcch_Config;
	PCCH_Config_t	 pcch_Config;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	struct DownlinkConfigCommonSIB__ext1 {
		struct PEI_Config_r17	*pei_Config_r17;	/* OPTIONAL */
		struct BWP_DownlinkCommon	*initialDownlinkBWP_RedCap_r17;	/* OPTIONAL */
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *ext1;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DownlinkConfigCommonSIB_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DownlinkConfigCommonSIB;
extern asn_SEQUENCE_specifics_t asn_SPC_DownlinkConfigCommonSIB_specs_1;
extern asn_TYPE_member_t asn_MBR_DownlinkConfigCommonSIB_1[5];

#ifdef __cplusplus
}
#endif

#endif	/* _DownlinkConfigCommonSIB_H_ */
#include <asn_internal.h>
