/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "nr-rrc-17.3.0.asn1"
 * 	`asn1c -no-gen-BER -no-gen-OER -no-gen-XER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -S /home/amd/wrk/asn1c_oai/skeletons/`
 */

#ifndef	_EpochTime_r17_H_
#define	_EpochTime_r17_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* EpochTime-r17 */
typedef struct EpochTime_r17 {
	long	 sfn_r17;
	long	 subFrameNR_r17;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} EpochTime_r17_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_EpochTime_r17;
extern asn_SEQUENCE_specifics_t asn_SPC_EpochTime_r17_specs_1;
extern asn_TYPE_member_t asn_MBR_EpochTime_r17_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _EpochTime_r17_H_ */
#include <asn_internal.h>
