/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "nr-rrc-17.3.0.asn1"
 * 	`asn1c -no-gen-BER -no-gen-OER -no-gen-XER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -S /home/amd/wrk/asn1c_oai/skeletons/`
 */

#ifndef	_FailureInformation_v1610_IEs_H_
#define	_FailureInformation_v1610_IEs_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct FailureInfoDAPS_r16;

/* FailureInformation-v1610-IEs */
typedef struct FailureInformation_v1610_IEs {
	struct FailureInfoDAPS_r16	*failureInfoDAPS_r16;	/* OPTIONAL */
	struct FailureInformation_v1610_IEs__nonCriticalExtension {
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *nonCriticalExtension;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} FailureInformation_v1610_IEs_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_FailureInformation_v1610_IEs;
extern asn_SEQUENCE_specifics_t asn_SPC_FailureInformation_v1610_IEs_specs_1;
extern asn_TYPE_member_t asn_MBR_FailureInformation_v1610_IEs_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _FailureInformation_v1610_IEs_H_ */
#include <asn_internal.h>
