/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "nr-rrc-17.3.0.asn1"
 * 	`asn1c -no-gen-BER -no-gen-OER -no-gen-XER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -S /home/amd/wrk/asn1c_oai/skeletons/`
 */

#ifndef	_FeatureSetUplinkPerCC_v1700_H_
#define	_FeatureSetUplinkPerCC_v1700_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum FeatureSetUplinkPerCC_v1700__mTRP_PUSCH_RepetitionTypeB_r17 {
	FeatureSetUplinkPerCC_v1700__mTRP_PUSCH_RepetitionTypeB_r17_n1	= 0,
	FeatureSetUplinkPerCC_v1700__mTRP_PUSCH_RepetitionTypeB_r17_n2	= 1,
	FeatureSetUplinkPerCC_v1700__mTRP_PUSCH_RepetitionTypeB_r17_n3	= 2,
	FeatureSetUplinkPerCC_v1700__mTRP_PUSCH_RepetitionTypeB_r17_n4	= 3
} e_FeatureSetUplinkPerCC_v1700__mTRP_PUSCH_RepetitionTypeB_r17;
typedef enum FeatureSetUplinkPerCC_v1700__mTRP_PUSCH_TypeB_CB_r17 {
	FeatureSetUplinkPerCC_v1700__mTRP_PUSCH_TypeB_CB_r17_n1	= 0,
	FeatureSetUplinkPerCC_v1700__mTRP_PUSCH_TypeB_CB_r17_n2	= 1,
	FeatureSetUplinkPerCC_v1700__mTRP_PUSCH_TypeB_CB_r17_n4	= 2
} e_FeatureSetUplinkPerCC_v1700__mTRP_PUSCH_TypeB_CB_r17;

/* Forward declarations */
struct SupportedBandwidth_v1700;

/* FeatureSetUplinkPerCC-v1700 */
typedef struct FeatureSetUplinkPerCC_v1700 {
	struct SupportedBandwidth_v1700	*supportedMinBandwidthUL_r17;	/* OPTIONAL */
	long	*mTRP_PUSCH_RepetitionTypeB_r17;	/* OPTIONAL */
	long	*mTRP_PUSCH_TypeB_CB_r17;	/* OPTIONAL */
	struct SupportedBandwidth_v1700	*supportedBandwidthUL_v1710;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} FeatureSetUplinkPerCC_v1700_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_mTRP_PUSCH_RepetitionTypeB_r17_3;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_mTRP_PUSCH_TypeB_CB_r17_8;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_FeatureSetUplinkPerCC_v1700;
extern asn_SEQUENCE_specifics_t asn_SPC_FeatureSetUplinkPerCC_v1700_specs_1;
extern asn_TYPE_member_t asn_MBR_FeatureSetUplinkPerCC_v1700_1[4];

#ifdef __cplusplus
}
#endif

#endif	/* _FeatureSetUplinkPerCC_v1700_H_ */
#include <asn_internal.h>
