/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "nr-rrc-17.3.0.asn1"
 * 	`asn1c -no-gen-BER -no-gen-OER -no-gen-XER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -S /home/amd/wrk/asn1c_oai/skeletons/`
 */

#ifndef	_FreqSeparationClass_H_
#define	_FreqSeparationClass_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum FreqSeparationClass {
	FreqSeparationClass_mhz800	= 0,
	FreqSeparationClass_mhz1200	= 1,
	FreqSeparationClass_mhz1400	= 2,
	/*
	 * Enumeration is extensible
	 */
	FreqSeparationClass_mhz400_v1650	= 3,
	FreqSeparationClass_mhz600_v1650	= 4
} e_FreqSeparationClass;

/* FreqSeparationClass */
typedef long	 FreqSeparationClass_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_FreqSeparationClass_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_FreqSeparationClass;
extern const asn_INTEGER_specifics_t asn_SPC_FreqSeparationClass_specs_1;
asn_struct_free_f FreqSeparationClass_free;
asn_struct_print_f FreqSeparationClass_print;
asn_constr_check_f FreqSeparationClass_constraint;
jer_type_encoder_f FreqSeparationClass_encode_jer;
per_type_decoder_f FreqSeparationClass_decode_uper;
per_type_encoder_f FreqSeparationClass_encode_uper;
per_type_decoder_f FreqSeparationClass_decode_aper;
per_type_encoder_f FreqSeparationClass_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _FreqSeparationClass_H_ */
#include <asn_internal.h>
