/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "nr-rrc-17.3.0.asn1"
 * 	`asn1c -no-gen-BER -no-gen-OER -no-gen-XER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -S /home/amd/wrk/asn1c_oai/skeletons/`
 */

#ifndef	_FreqPriorityDedicatedSlicing_r17_H_
#define	_FreqPriorityDedicatedSlicing_r17_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ARFCN-ValueNR.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct SliceInfoListDedicated_r17;

/* FreqPriorityDedicatedSlicing-r17 */
typedef struct FreqPriorityDedicatedSlicing_r17 {
	ARFCN_ValueNR_t	 dl_ExplicitCarrierFreq_r17;
	struct SliceInfoListDedicated_r17	*sliceInfoListDedicated_r17;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} FreqPriorityDedicatedSlicing_r17_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_FreqPriorityDedicatedSlicing_r17;
extern asn_SEQUENCE_specifics_t asn_SPC_FreqPriorityDedicatedSlicing_r17_specs_1;
extern asn_TYPE_member_t asn_MBR_FreqPriorityDedicatedSlicing_r17_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _FreqPriorityDedicatedSlicing_r17_H_ */
#include <asn_internal.h>
