/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "nr-rrc-17.3.0.asn1"
 * 	`asn1c -no-gen-BER -no-gen-OER -no-gen-XER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -S /home/amd/wrk/asn1c_oai/skeletons/`
 */

#ifndef	_GIN_Element_r17_H_
#define	_GIN_Element_r17_H_


#include <asn_application.h>

/* Including external dependencies */
#include "PLMN-Identity.h"
#include "NID-r16.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* GIN-Element-r17 */
typedef struct GIN_Element_r17 {
	PLMN_Identity_t	 plmn_Identity_r17;
	struct GIN_Element_r17__nid_List_r17 {
		A_SEQUENCE_OF(NID_r16_t) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} nid_List_r17;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} GIN_Element_r17_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_GIN_Element_r17;
extern asn_SEQUENCE_specifics_t asn_SPC_GIN_Element_r17_specs_1;
extern asn_TYPE_member_t asn_MBR_GIN_Element_r17_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _GIN_Element_r17_H_ */
#include <asn_internal.h>
