/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "nr-rrc-17.3.0.asn1"
 * 	`asn1c -no-gen-BER -no-gen-OER -no-gen-XER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -S /home/amd/wrk/asn1c_oai/skeletons/`
 */

#ifndef	_HRNN_List_r16_H_
#define	_HRNN_List_r16_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct HRNN_r16;

/* HRNN-List-r16 */
typedef struct HRNN_List_r16 {
	A_SEQUENCE_OF(struct HRNN_r16) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} HRNN_List_r16_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_HRNN_List_r16;
extern asn_SET_OF_specifics_t asn_SPC_HRNN_List_r16_specs_1;
extern asn_TYPE_member_t asn_MBR_HRNN_List_r16_1[1];
extern asn_per_constraints_t asn_PER_type_HRNN_List_r16_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _HRNN_List_r16_H_ */
#include <asn_internal.h>
