/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "nr-rrc-17.3.0.asn1"
 * 	`asn1c -no-gen-BER -no-gen-OER -no-gen-XER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -S /home/amd/wrk/asn1c_oai/skeletons/`
 */

#ifndef	_IDC_Assistance_r16_H_
#define	_IDC_Assistance_r16_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct AffectedCarrierFreqList_r16;
struct AffectedCarrierFreqCombList_r16;

/* IDC-Assistance-r16 */
typedef struct IDC_Assistance_r16 {
	struct AffectedCarrierFreqList_r16	*affectedCarrierFreqList_r16;	/* OPTIONAL */
	struct AffectedCarrierFreqCombList_r16	*affectedCarrierFreqCombList_r16;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} IDC_Assistance_r16_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_IDC_Assistance_r16;
extern asn_SEQUENCE_specifics_t asn_SPC_IDC_Assistance_r16_specs_1;
extern asn_TYPE_member_t asn_MBR_IDC_Assistance_r16_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _IDC_Assistance_r16_H_ */
#include <asn_internal.h>
