/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "nr-rrc-17.3.0.asn1"
 * 	`asn1c -no-gen-BER -no-gen-OER -no-gen-XER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -S /home/amd/wrk/asn1c_oai/skeletons/`
 */

#ifndef	_InterFreqCarrierFreqInfo_v1610_H_
#define	_InterFreqCarrierFreqInfo_v1610_H_


#include <asn_application.h>

/* Including external dependencies */
#include "SSB-PositionQCL-Relation-r16.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct InterFreqNeighCellList_v1610;
struct SSB_MTC2_LP_r16;
struct InterFreqAllowedCellList_r16;
struct InterFreqCAG_CellListPerPLMN_r16;

/* InterFreqCarrierFreqInfo-v1610 */
typedef struct InterFreqCarrierFreqInfo_v1610 {
	struct InterFreqNeighCellList_v1610	*interFreqNeighCellList_v1610;	/* OPTIONAL */
	struct SSB_MTC2_LP_r16	*smtc2_LP_r16;	/* OPTIONAL */
	struct InterFreqAllowedCellList_r16	*interFreqAllowedCellList_r16;	/* OPTIONAL */
	SSB_PositionQCL_Relation_r16_t	*ssb_PositionQCL_Common_r16;	/* OPTIONAL */
	struct InterFreqCarrierFreqInfo_v1610__interFreqCAG_CellList_r16 {
		A_SEQUENCE_OF(struct InterFreqCAG_CellListPerPLMN_r16) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *interFreqCAG_CellList_r16;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} InterFreqCarrierFreqInfo_v1610_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_InterFreqCarrierFreqInfo_v1610;
extern asn_SEQUENCE_specifics_t asn_SPC_InterFreqCarrierFreqInfo_v1610_specs_1;
extern asn_TYPE_member_t asn_MBR_InterFreqCarrierFreqInfo_v1610_1[5];

#ifdef __cplusplus
}
#endif

#endif	/* _InterFreqCarrierFreqInfo_v1610_H_ */
#include <asn_internal.h>
