/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "nr-rrc-17.3.0.asn1"
 * 	`asn1c -no-gen-BER -no-gen-OER -no-gen-XER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -S /home/amd/wrk/asn1c_oai/skeletons/`
 */

#ifndef	_MAC_Parameters_v1610_H_
#define	_MAC_Parameters_v1610_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct MAC_ParametersFRX_Diff_r16;

/* MAC-Parameters-v1610 */
typedef struct MAC_Parameters_v1610 {
	struct MAC_ParametersFRX_Diff_r16	*mac_ParametersFRX_Diff_r16;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MAC_Parameters_v1610_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MAC_Parameters_v1610;
extern asn_SEQUENCE_specifics_t asn_SPC_MAC_Parameters_v1610_specs_1;
extern asn_TYPE_member_t asn_MBR_MAC_Parameters_v1610_1[1];

#ifdef __cplusplus
}
#endif

#endif	/* _MAC_Parameters_v1610_H_ */
#include <asn_internal.h>
