/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "nr-rrc-17.3.0.asn1"
 * 	`asn1c -no-gen-BER -no-gen-OER -no-gen-XER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -S /home/amd/wrk/asn1c_oai/skeletons/`
 */

#ifndef	_MBSBroadcastConfiguration_r17_IEs_H_
#define	_MBSBroadcastConfiguration_r17_IEs_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct MBS_SessionInfoList_r17;
struct MBS_NeighbourCellList_r17;
struct PDSCH_ConfigBroadcast_r17;
struct MTCH_SSB_MappingWindowList_r17;
struct DRX_ConfigPTM_r17;

/* MBSBroadcastConfiguration-r17-IEs */
typedef struct MBSBroadcastConfiguration_r17_IEs {
	struct MBS_SessionInfoList_r17	*mbs_SessionInfoList_r17;	/* OPTIONAL */
	struct MBS_NeighbourCellList_r17	*mbs_NeighbourCellList_r17;	/* OPTIONAL */
	struct MBSBroadcastConfiguration_r17_IEs__drx_ConfigPTM_List_r17 {
		A_SEQUENCE_OF(struct DRX_ConfigPTM_r17) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *drx_ConfigPTM_List_r17;
	struct PDSCH_ConfigBroadcast_r17	*pdsch_ConfigMTCH_r17;	/* OPTIONAL */
	struct MTCH_SSB_MappingWindowList_r17	*mtch_SSB_MappingWindowList_r17;	/* OPTIONAL */
	OCTET_STRING_t	*lateNonCriticalExtension;	/* OPTIONAL */
	struct MBSBroadcastConfiguration_r17_IEs__nonCriticalExtension {
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *nonCriticalExtension;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MBSBroadcastConfiguration_r17_IEs_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MBSBroadcastConfiguration_r17_IEs;
extern asn_SEQUENCE_specifics_t asn_SPC_MBSBroadcastConfiguration_r17_IEs_specs_1;
extern asn_TYPE_member_t asn_MBR_MBSBroadcastConfiguration_r17_IEs_1[7];

#ifdef __cplusplus
}
#endif

#endif	/* _MBSBroadcastConfiguration_r17_IEs_H_ */
#include <asn_internal.h>
