/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "nr-rrc-17.3.0.asn1"
 * 	`asn1c -no-gen-BER -no-gen-OER -no-gen-XER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -S /home/amd/wrk/asn1c_oai/skeletons/`
 */

#ifndef	_MCCH_Message_r17_H_
#define	_MCCH_Message_r17_H_


#include <asn_application.h>

/* Including external dependencies */
#include "MCCH-MessageType-r17.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* MCCH-Message-r17 */
typedef struct MCCH_Message_r17 {
	MCCH_MessageType_r17_t	 message;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MCCH_Message_r17_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MCCH_Message_r17;

#ifdef __cplusplus
}
#endif

#endif	/* _MCCH_Message_r17_H_ */
#include <asn_internal.h>
