/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "nr-rrc-17.3.0.asn1"
 * 	`asn1c -no-gen-BER -no-gen-OER -no-gen-XER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -S /home/amd/wrk/asn1c_oai/skeletons/`
 */

#ifndef	_MeasGapConfig_H_
#define	_MeasGapConfig_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_SEQUENCE.h>
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include "MeasGapId-r17.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct SetupRelease_GapConfig;
struct PosMeasGapPreConfigToAddModList_r17;
struct PosMeasGapPreConfigToReleaseList_r17;
struct GapConfig_r17;

/* MeasGapConfig */
typedef struct MeasGapConfig {
	struct SetupRelease_GapConfig	*gapFR2;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	struct MeasGapConfig__ext1 {
		struct SetupRelease_GapConfig	*gapFR1;	/* OPTIONAL */
		struct SetupRelease_GapConfig	*gapUE;	/* OPTIONAL */
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *ext1;
	struct MeasGapConfig__ext2 {
		struct MeasGapConfig__ext2__gapToAddModList_r17 {
			A_SEQUENCE_OF(struct GapConfig_r17) list;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} *gapToAddModList_r17;
		struct MeasGapConfig__ext2__gapToReleaseList_r17 {
			A_SEQUENCE_OF(MeasGapId_r17_t) list;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} *gapToReleaseList_r17;
		struct PosMeasGapPreConfigToAddModList_r17	*posMeasGapPreConfigToAddModList_r17;	/* OPTIONAL */
		struct PosMeasGapPreConfigToReleaseList_r17	*posMeasGapPreConfigToReleaseList_r17;	/* OPTIONAL */
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *ext2;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MeasGapConfig_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MeasGapConfig;
extern asn_SEQUENCE_specifics_t asn_SPC_MeasGapConfig_specs_1;
extern asn_TYPE_member_t asn_MBR_MeasGapConfig_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _MeasGapConfig_H_ */
#include <asn_internal.h>
