/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "nr-rrc-17.3.0.asn1"
 * 	`asn1c -no-gen-BER -no-gen-OER -no-gen-XER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -S /home/amd/wrk/asn1c_oai/skeletons/`
 */

#ifndef	_MeasAndMobParametersMRDC_Common_v1730_H_
#define	_MeasAndMobParametersMRDC_Common_v1730_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* MeasAndMobParametersMRDC-Common-v1730 */
typedef struct MeasAndMobParametersMRDC_Common_v1730 {
	struct MeasAndMobParametersMRDC_Common_v1730__independentGapConfig_maxCC_r17 {
		long	*fr1_Only_r17;	/* OPTIONAL */
		long	*fr2_Only_r17;	/* OPTIONAL */
		long	*fr1_AndFR2_r17;	/* OPTIONAL */
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} independentGapConfig_maxCC_r17;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MeasAndMobParametersMRDC_Common_v1730_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MeasAndMobParametersMRDC_Common_v1730;
extern asn_SEQUENCE_specifics_t asn_SPC_MeasAndMobParametersMRDC_Common_v1730_specs_1;
extern asn_TYPE_member_t asn_MBR_MeasAndMobParametersMRDC_Common_v1730_1[1];

#ifdef __cplusplus
}
#endif

#endif	/* _MeasAndMobParametersMRDC_Common_v1730_H_ */
#include <asn_internal.h>
