/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-InterNodeDefinitions"
 * 	found in "nr-rrc-17.3.0.asn1"
 * 	`asn1c -no-gen-BER -no-gen-OER -no-gen-XER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -S /home/amd/wrk/asn1c_oai/skeletons/`
 */

#ifndef	_MRDC_AssistanceInfo_H_
#define	_MRDC_AssistanceInfo_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <OCTET_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct AffectedCarrierFreqCombInfoMRDC;

/* MRDC-AssistanceInfo */
typedef struct MRDC_AssistanceInfo {
	struct MRDC_AssistanceInfo__affectedCarrierFreqCombInfoListMRDC {
		A_SEQUENCE_OF(struct AffectedCarrierFreqCombInfoMRDC) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} affectedCarrierFreqCombInfoListMRDC;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	struct MRDC_AssistanceInfo__ext1 {
		OCTET_STRING_t	*overheatingAssistanceSCG_r16;	/* OPTIONAL */
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *ext1;
	struct MRDC_AssistanceInfo__ext2 {
		OCTET_STRING_t	*overheatingAssistanceSCG_FR2_2_r17;	/* OPTIONAL */
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *ext2;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MRDC_AssistanceInfo_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MRDC_AssistanceInfo;
extern asn_SEQUENCE_specifics_t asn_SPC_MRDC_AssistanceInfo_specs_1;
extern asn_TYPE_member_t asn_MBR_MRDC_AssistanceInfo_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _MRDC_AssistanceInfo_H_ */
#include <asn_internal.h>
