/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "nr-rrc-17.3.0.asn1"
 * 	`asn1c -no-gen-BER -no-gen-OER -no-gen-XER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -S /home/amd/wrk/asn1c_oai/skeletons/`
 */

#ifndef	_MRDC_Parameters_v1700_H_
#define	_MRDC_Parameters_v1700_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum MRDC_Parameters_v1700__condPSCellAdditionENDC_r17 {
	MRDC_Parameters_v1700__condPSCellAdditionENDC_r17_supported	= 0
} e_MRDC_Parameters_v1700__condPSCellAdditionENDC_r17;
typedef enum MRDC_Parameters_v1700__scg_ActivationDeactivationENDC_r17 {
	MRDC_Parameters_v1700__scg_ActivationDeactivationENDC_r17_supported	= 0
} e_MRDC_Parameters_v1700__scg_ActivationDeactivationENDC_r17;
typedef enum MRDC_Parameters_v1700__scg_ActivationDeactivationResumeENDC_r17 {
	MRDC_Parameters_v1700__scg_ActivationDeactivationResumeENDC_r17_supported	= 0
} e_MRDC_Parameters_v1700__scg_ActivationDeactivationResumeENDC_r17;

/* MRDC-Parameters-v1700 */
typedef struct MRDC_Parameters_v1700 {
	long	*condPSCellAdditionENDC_r17;	/* OPTIONAL */
	long	*scg_ActivationDeactivationENDC_r17;	/* OPTIONAL */
	long	*scg_ActivationDeactivationResumeENDC_r17;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MRDC_Parameters_v1700_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_condPSCellAdditionENDC_r17_2;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_scg_ActivationDeactivationENDC_r17_4;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_scg_ActivationDeactivationResumeENDC_r17_6;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_MRDC_Parameters_v1700;
extern asn_SEQUENCE_specifics_t asn_SPC_MRDC_Parameters_v1700_specs_1;
extern asn_TYPE_member_t asn_MBR_MRDC_Parameters_v1700_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _MRDC_Parameters_v1700_H_ */
#include <asn_internal.h>
