/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "nr-rrc-17.3.0.asn1"
 * 	`asn1c -no-gen-BER -no-gen-OER -no-gen-XER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -S /home/amd/wrk/asn1c_oai/skeletons/`
 */

#ifndef	_NR_DL_PRS_PDC_Info_r17_H_
#define	_NR_DL_PRS_PDC_Info_r17_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct NR_DL_PRS_PDC_ResourceSet_r17;

/* NR-DL-PRS-PDC-Info-r17 */
typedef struct NR_DL_PRS_PDC_Info_r17 {
	struct NR_DL_PRS_PDC_ResourceSet_r17	*nr_DL_PRS_PDC_ResourceSet_r17;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NR_DL_PRS_PDC_Info_r17_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NR_DL_PRS_PDC_Info_r17;
extern asn_SEQUENCE_specifics_t asn_SPC_NR_DL_PRS_PDC_Info_r17_specs_1;
extern asn_TYPE_member_t asn_MBR_NR_DL_PRS_PDC_Info_r17_1[1];

#ifdef __cplusplus
}
#endif

#endif	/* _NR_DL_PRS_PDC_Info_r17_H_ */
#include <asn_internal.h>
