/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "nr-rrc-17.3.0.asn1"
 * 	`asn1c -no-gen-BER -no-gen-OER -no-gen-XER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -S /home/amd/wrk/asn1c_oai/skeletons/`
 */

#ifndef	_NTN_Parameters_r17_H_
#define	_NTN_Parameters_r17_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NTN_Parameters_r17__inactiveStateNTN_r17 {
	NTN_Parameters_r17__inactiveStateNTN_r17_supported	= 0
} e_NTN_Parameters_r17__inactiveStateNTN_r17;
typedef enum NTN_Parameters_r17__ra_SDT_NTN_r17 {
	NTN_Parameters_r17__ra_SDT_NTN_r17_supported	= 0
} e_NTN_Parameters_r17__ra_SDT_NTN_r17;
typedef enum NTN_Parameters_r17__srb_SDT_NTN_r17 {
	NTN_Parameters_r17__srb_SDT_NTN_r17_supported	= 0
} e_NTN_Parameters_r17__srb_SDT_NTN_r17;

/* Forward declarations */
struct MeasAndMobParameters;
struct MAC_Parameters;
struct Phy_Parameters;
struct UE_NR_CapabilityAddXDD_Mode;
struct UE_NR_CapabilityAddFRX_Mode;
struct UE_BasedPerfMeas_Parameters_r16;
struct SON_Parameters_r16;

/* NTN-Parameters-r17 */
typedef struct NTN_Parameters_r17 {
	long	*inactiveStateNTN_r17;	/* OPTIONAL */
	long	*ra_SDT_NTN_r17;	/* OPTIONAL */
	long	*srb_SDT_NTN_r17;	/* OPTIONAL */
	struct MeasAndMobParameters	*measAndMobParametersNTN_r17;	/* OPTIONAL */
	struct MAC_Parameters	*mac_ParametersNTN_r17;	/* OPTIONAL */
	struct Phy_Parameters	*phy_ParametersNTN_r17;	/* OPTIONAL */
	struct UE_NR_CapabilityAddXDD_Mode	*fdd_Add_UE_NR_CapabilitiesNTN_r17;	/* OPTIONAL */
	struct UE_NR_CapabilityAddFRX_Mode	*fr1_Add_UE_NR_CapabilitiesNTN_r17;	/* OPTIONAL */
	struct UE_BasedPerfMeas_Parameters_r16	*ue_BasedPerfMeas_ParametersNTN_r17;	/* OPTIONAL */
	struct SON_Parameters_r16	*son_ParametersNTN_r17;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NTN_Parameters_r17_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_inactiveStateNTN_r17_2;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_ra_SDT_NTN_r17_4;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_srb_SDT_NTN_r17_6;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_NTN_Parameters_r17;
extern asn_SEQUENCE_specifics_t asn_SPC_NTN_Parameters_r17_specs_1;
extern asn_TYPE_member_t asn_MBR_NTN_Parameters_r17_1[10];

#ifdef __cplusplus
}
#endif

#endif	/* _NTN_Parameters_r17_H_ */
#include <asn_internal.h>
