/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "nr-rrc-17.3.0.asn1"
 * 	`asn1c -no-gen-BER -no-gen-OER -no-gen-XER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -S /home/amd/wrk/asn1c_oai/skeletons/`
 */

#ifndef	_PDCCH_BlindDetectionMixed1_r17_H_
#define	_PDCCH_BlindDetectionMixed1_r17_H_


#include <asn_application.h>

/* Including external dependencies */
#include "PDCCH-BlindDetectionCG-UE-Mixed1-r17.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct PDCCH_BlindDetectionCA_Mixed1_r17;

/* PDCCH-BlindDetectionMixed1-r17 */
typedef struct PDCCH_BlindDetectionMixed1_r17 {
	struct PDCCH_BlindDetectionCA_Mixed1_r17	*pdcch_BlindDetectionCA_Mixed1_r17;	/* OPTIONAL */
	struct PDCCH_BlindDetectionMixed1_r17__pdcch_BlindDetectionCG_UE_Mixed1_r17 {
		PDCCH_BlindDetectionCG_UE_Mixed1_r17_t	 pdcch_BlindDetectionMCG_UE_Mixed1_v17;
		PDCCH_BlindDetectionCG_UE_Mixed1_r17_t	 pdcch_BlindDetectionSCG_UE_Mixed1_v17;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *pdcch_BlindDetectionCG_UE_Mixed1_r17;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PDCCH_BlindDetectionMixed1_r17_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PDCCH_BlindDetectionMixed1_r17;
extern asn_SEQUENCE_specifics_t asn_SPC_PDCCH_BlindDetectionMixed1_r17_specs_1;
extern asn_TYPE_member_t asn_MBR_PDCCH_BlindDetectionMixed1_r17_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _PDCCH_BlindDetectionMixed1_r17_H_ */
#include <asn_internal.h>
