/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "nr-rrc-17.3.0.asn1"
 * 	`asn1c -no-gen-BER -no-gen-OER -no-gen-XER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -S /home/amd/wrk/asn1c_oai/skeletons/`
 */

#ifndef	_PerRAInfoList_v1660_H_
#define	_PerRAInfoList_v1660_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct PerRACSI_RSInfo_v1660;

/* PerRAInfoList-v1660 */
typedef struct PerRAInfoList_v1660 {
	A_SEQUENCE_OF(struct PerRACSI_RSInfo_v1660) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PerRAInfoList_v1660_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PerRAInfoList_v1660;
extern asn_SET_OF_specifics_t asn_SPC_PerRAInfoList_v1660_specs_1;
extern asn_TYPE_member_t asn_MBR_PerRAInfoList_v1660_1[1];
extern asn_per_constraints_t asn_PER_type_PerRAInfoList_v1660_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _PerRAInfoList_v1660_H_ */
#include <asn_internal.h>
