/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "nr-rrc-17.3.0.asn1"
 * 	`asn1c -no-gen-BER -no-gen-OER -no-gen-XER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -S /home/amd/wrk/asn1c_oai/skeletons/`
 */

#ifndef	_Phy_ParametersMRDC_H_
#define	_Phy_ParametersMRDC_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Phy_ParametersMRDC__ext2__tdd_PCellUL_TX_AllUL_Subframe_r16 {
	Phy_ParametersMRDC__ext2__tdd_PCellUL_TX_AllUL_Subframe_r16_supported	= 0
} e_Phy_ParametersMRDC__ext2__tdd_PCellUL_TX_AllUL_Subframe_r16;
typedef enum Phy_ParametersMRDC__ext2__fdd_PCellUL_TX_AllUL_Subframe_r16 {
	Phy_ParametersMRDC__ext2__fdd_PCellUL_TX_AllUL_Subframe_r16_supported	= 0
} e_Phy_ParametersMRDC__ext2__fdd_PCellUL_TX_AllUL_Subframe_r16;

/* Forward declarations */
struct NAICS_Capability_Entry;
struct CarrierAggregationVariant;

/* Phy-ParametersMRDC */
typedef struct Phy_ParametersMRDC {
	struct Phy_ParametersMRDC__naics_Capability_List {
		A_SEQUENCE_OF(struct NAICS_Capability_Entry) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *naics_Capability_List;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	struct Phy_ParametersMRDC__ext1 {
		struct CarrierAggregationVariant	*spCellPlacement;	/* OPTIONAL */
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *ext1;
	struct Phy_ParametersMRDC__ext2 {
		long	*tdd_PCellUL_TX_AllUL_Subframe_r16;	/* OPTIONAL */
		long	*fdd_PCellUL_TX_AllUL_Subframe_r16;	/* OPTIONAL */
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *ext2;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Phy_ParametersMRDC_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_tdd_PCellUL_TX_AllUL_Subframe_r16_8;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_fdd_PCellUL_TX_AllUL_Subframe_r16_10;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_Phy_ParametersMRDC;
extern asn_SEQUENCE_specifics_t asn_SPC_Phy_ParametersMRDC_specs_1;
extern asn_TYPE_member_t asn_MBR_Phy_ParametersMRDC_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _Phy_ParametersMRDC_H_ */
#include <asn_internal.h>
