/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "nr-rrc-17.3.0.asn1"
 * 	`asn1c -no-gen-BER -no-gen-OER -no-gen-XER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -S /home/amd/wrk/asn1c_oai/skeletons/`
 */

#ifndef	_PortIndex8_H_
#define	_PortIndex8_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* PortIndex8 */
typedef long	 PortIndex8_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_PortIndex8_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_PortIndex8;
asn_struct_free_f PortIndex8_free;
asn_struct_print_f PortIndex8_print;
asn_constr_check_f PortIndex8_constraint;
jer_type_encoder_f PortIndex8_encode_jer;
per_type_decoder_f PortIndex8_decode_uper;
per_type_encoder_f PortIndex8_encode_uper;
per_type_decoder_f PortIndex8_decode_aper;
per_type_encoder_f PortIndex8_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _PortIndex8_H_ */
#include <asn_internal.h>
