/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "nr-rrc-17.3.0.asn1"
 * 	`asn1c -no-gen-BER -no-gen-OER -no-gen-XER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -S /home/amd/wrk/asn1c_oai/skeletons/`
 */

#ifndef	_RACH_ConfigDedicated_H_
#define	_RACH_ConfigDedicated_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct CFRA;
struct RA_Prioritization;
struct CFRA_TwoStep_r16;

/* RACH-ConfigDedicated */
typedef struct RACH_ConfigDedicated {
	struct CFRA	*cfra;	/* OPTIONAL */
	struct RA_Prioritization	*ra_Prioritization;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	struct RACH_ConfigDedicated__ext1 {
		struct RA_Prioritization	*ra_PrioritizationTwoStep_r16;	/* OPTIONAL */
		struct CFRA_TwoStep_r16	*cfra_TwoStep_r16;	/* OPTIONAL */
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *ext1;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RACH_ConfigDedicated_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RACH_ConfigDedicated;
extern asn_SEQUENCE_specifics_t asn_SPC_RACH_ConfigDedicated_specs_1;
extern asn_TYPE_member_t asn_MBR_RACH_ConfigDedicated_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _RACH_ConfigDedicated_H_ */
#include <asn_internal.h>
