/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "nr-rrc-17.3.0.asn1"
 * 	`asn1c -no-gen-BER -no-gen-OER -no-gen-XER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -S /home/amd/wrk/asn1c_oai/skeletons/`
 */

#ifndef	_RangeToBestCell_H_
#define	_RangeToBestCell_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Q-OffsetRange.h"

#ifdef __cplusplus
extern "C" {
#endif

/* RangeToBestCell */
typedef Q_OffsetRange_t	 RangeToBestCell_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_RangeToBestCell_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_RangeToBestCell;
asn_struct_free_f RangeToBestCell_free;
asn_struct_print_f RangeToBestCell_print;
asn_constr_check_f RangeToBestCell_constraint;
jer_type_encoder_f RangeToBestCell_encode_jer;
per_type_decoder_f RangeToBestCell_decode_uper;
per_type_encoder_f RangeToBestCell_encode_uper;
per_type_decoder_f RangeToBestCell_decode_aper;
per_type_encoder_f RangeToBestCell_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _RangeToBestCell_H_ */
#include <asn_internal.h>
