/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "nr-rrc-17.3.0.asn1"
 * 	`asn1c -no-gen-BER -no-gen-OER -no-gen-XER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -S /home/amd/wrk/asn1c_oai/skeletons/`
 */

#ifndef	_RRCReconfiguration_v1610_IEs_H_
#define	_RRCReconfiguration_v1610_IEs_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>
#include <OCTET_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum RRCReconfiguration_v1610_IEs__daps_SourceRelease_r16 {
	RRCReconfiguration_v1610_IEs__daps_SourceRelease_r16_true	= 0
} e_RRCReconfiguration_v1610_IEs__daps_SourceRelease_r16;

/* Forward declarations */
struct OtherConfig_v1610;
struct SetupRelease_BAP_Config_r16;
struct IAB_IP_AddressConfigurationList_r16;
struct ConditionalReconfiguration_r16;
struct SetupRelease_T316_r16;
struct SetupRelease_NeedForGapsConfigNR_r16;
struct SetupRelease_OnDemandSIB_Request_r16;
struct SetupRelease_SL_ConfigDedicatedNR_r16;
struct SetupRelease_SL_ConfigDedicatedEUTRA_Info_r16;
struct SSB_MTC;
struct RRCReconfiguration_v1700_IEs;

/* RRCReconfiguration-v1610-IEs */
typedef struct RRCReconfiguration_v1610_IEs {
	struct OtherConfig_v1610	*otherConfig_v1610;	/* OPTIONAL */
	struct SetupRelease_BAP_Config_r16	*bap_Config_r16;	/* OPTIONAL */
	struct IAB_IP_AddressConfigurationList_r16	*iab_IP_AddressConfigurationList_r16;	/* OPTIONAL */
	struct ConditionalReconfiguration_r16	*conditionalReconfiguration_r16;	/* OPTIONAL */
	long	*daps_SourceRelease_r16;	/* OPTIONAL */
	struct SetupRelease_T316_r16	*t316_r16;	/* OPTIONAL */
	struct SetupRelease_NeedForGapsConfigNR_r16	*needForGapsConfigNR_r16;	/* OPTIONAL */
	struct SetupRelease_OnDemandSIB_Request_r16	*onDemandSIB_Request_r16;	/* OPTIONAL */
	OCTET_STRING_t	*dedicatedPosSysInfoDelivery_r16;	/* OPTIONAL */
	struct SetupRelease_SL_ConfigDedicatedNR_r16	*sl_ConfigDedicatedNR_r16;	/* OPTIONAL */
	struct SetupRelease_SL_ConfigDedicatedEUTRA_Info_r16	*sl_ConfigDedicatedEUTRA_Info_r16;	/* OPTIONAL */
	struct SSB_MTC	*targetCellSMTC_SCG_r16;	/* OPTIONAL */
	struct RRCReconfiguration_v1700_IEs	*nonCriticalExtension;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RRCReconfiguration_v1610_IEs_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_daps_SourceRelease_r16_6;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_RRCReconfiguration_v1610_IEs;
extern asn_SEQUENCE_specifics_t asn_SPC_RRCReconfiguration_v1610_IEs_specs_1;
extern asn_TYPE_member_t asn_MBR_RRCReconfiguration_v1610_IEs_1[13];

#ifdef __cplusplus
}
#endif

#endif	/* _RRCReconfiguration_v1610_IEs_H_ */
#include <asn_internal.h>
