/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "nr-rrc-17.3.0.asn1"
 * 	`asn1c -no-gen-BER -no-gen-OER -no-gen-XER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -S /home/amd/wrk/asn1c_oai/skeletons/`
 */

#ifndef	_RRCRelease_v1650_IEs_H_
#define	_RRCRelease_v1650_IEs_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum RRCRelease_v1650_IEs__mpsPriorityIndication_r16 {
	RRCRelease_v1650_IEs__mpsPriorityIndication_r16_true	= 0
} e_RRCRelease_v1650_IEs__mpsPriorityIndication_r16;

/* Forward declarations */
struct RRCRelease_v1710_IEs;

/* RRCRelease-v1650-IEs */
typedef struct RRCRelease_v1650_IEs {
	long	*mpsPriorityIndication_r16;	/* OPTIONAL */
	struct RRCRelease_v1710_IEs	*nonCriticalExtension;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RRCRelease_v1650_IEs_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_mpsPriorityIndication_r16_2;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_RRCRelease_v1650_IEs;
extern asn_SEQUENCE_specifics_t asn_SPC_RRCRelease_v1650_IEs_specs_1;
extern asn_TYPE_member_t asn_MBR_RRCRelease_v1650_IEs_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _RRCRelease_v1650_IEs_H_ */
#include <asn_internal.h>
