/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "PC5-RRC-Definitions"
 * 	found in "nr-rrc-17.3.0.asn1"
 * 	`asn1c -no-gen-BER -no-gen-OER -no-gen-XER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -S /home/amd/wrk/asn1c_oai/skeletons/`
 */

#ifndef	_RRCReconfigurationSidelink_H_
#define	_RRCReconfigurationSidelink_H_


#include <asn_application.h>

/* Including external dependencies */
#include "RRC-TransactionIdentifier.h"
#include <constr_SEQUENCE.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum RRCReconfigurationSidelink__criticalExtensions_PR {
	RRCReconfigurationSidelink__criticalExtensions_PR_NOTHING,	/* No components present */
	RRCReconfigurationSidelink__criticalExtensions_PR_rrcReconfigurationSidelink_r16,
	RRCReconfigurationSidelink__criticalExtensions_PR_criticalExtensionsFuture
} RRCReconfigurationSidelink__criticalExtensions_PR;

/* Forward declarations */
struct RRCReconfigurationSidelink_r16_IEs;

/* RRCReconfigurationSidelink */
typedef struct RRCReconfigurationSidelink {
	RRC_TransactionIdentifier_t	 rrc_TransactionIdentifier_r16;
	struct RRCReconfigurationSidelink__criticalExtensions {
		RRCReconfigurationSidelink__criticalExtensions_PR present;
		union RRCReconfigurationSidelink__criticalExtensions_u {
			struct RRCReconfigurationSidelink_r16_IEs	*rrcReconfigurationSidelink_r16;
			struct RRCReconfigurationSidelink__criticalExtensions__criticalExtensionsFuture {
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} *criticalExtensionsFuture;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} criticalExtensions;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RRCReconfigurationSidelink_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RRCReconfigurationSidelink;
extern asn_SEQUENCE_specifics_t asn_SPC_RRCReconfigurationSidelink_specs_1;
extern asn_TYPE_member_t asn_MBR_RRCReconfigurationSidelink_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _RRCReconfigurationSidelink_H_ */
#include <asn_internal.h>
