/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "nr-rrc-17.3.0.asn1"
 * 	`asn1c -no-gen-BER -no-gen-OER -no-gen-XER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -S /home/amd/wrk/asn1c_oai/skeletons/`
 */

#ifndef	_RRCResumeComplete_v1700_IEs_H_
#define	_RRCResumeComplete_v1700_IEs_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct NeedForGapNCSG_InfoNR_r17;
struct NeedForGapNCSG_InfoEUTRA_r17;
struct RRCResumeComplete_v1720_IEs;

/* RRCResumeComplete-v1700-IEs */
typedef struct RRCResumeComplete_v1700_IEs {
	struct NeedForGapNCSG_InfoNR_r17	*needForGapNCSG_InfoNR_r17;	/* OPTIONAL */
	struct NeedForGapNCSG_InfoEUTRA_r17	*needForGapNCSG_InfoEUTRA_r17;	/* OPTIONAL */
	struct RRCResumeComplete_v1720_IEs	*nonCriticalExtension;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RRCResumeComplete_v1700_IEs_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RRCResumeComplete_v1700_IEs;
extern asn_SEQUENCE_specifics_t asn_SPC_RRCResumeComplete_v1700_IEs_specs_1;
extern asn_TYPE_member_t asn_MBR_RRCResumeComplete_v1700_IEs_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _RRCResumeComplete_v1700_IEs_H_ */
#include <asn_internal.h>
