/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "PC5-RRC-Definitions"
 * 	found in "nr-rrc-17.3.0.asn1"
 * 	`asn1c -no-gen-BER -no-gen-OER -no-gen-XER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -S /home/amd/wrk/asn1c_oai/skeletons/`
 */

#ifndef	_RRCReconfigurationSidelink_v1700_IEs_H_
#define	_RRCReconfigurationSidelink_v1700_IEs_H_


#include <asn_application.h>

/* Including external dependencies */
#include "SL-RLC-ChannelID-r17.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct SetupRelease_SL_DRX_ConfigUC_r17;
struct SetupRelease_SL_LatencyBoundIUC_Report_r17;
struct SL_RLC_ChannelConfigPC5_r17;

/* RRCReconfigurationSidelink-v1700-IEs */
typedef struct RRCReconfigurationSidelink_v1700_IEs {
	struct SetupRelease_SL_DRX_ConfigUC_r17	*sl_DRX_ConfigUC_PC5_r17;	/* OPTIONAL */
	struct SetupRelease_SL_LatencyBoundIUC_Report_r17	*sl_LatencyBoundIUC_Report_r17;	/* OPTIONAL */
	struct RRCReconfigurationSidelink_v1700_IEs__sl_RLC_ChannelToReleaseListPC5_r17 {
		A_SEQUENCE_OF(SL_RLC_ChannelID_r17_t) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *sl_RLC_ChannelToReleaseListPC5_r17;
	struct RRCReconfigurationSidelink_v1700_IEs__sl_RLC_ChannelToAddModListPC5_r17 {
		A_SEQUENCE_OF(struct SL_RLC_ChannelConfigPC5_r17) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *sl_RLC_ChannelToAddModListPC5_r17;
	struct RRCReconfigurationSidelink_v1700_IEs__nonCriticalExtension {
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *nonCriticalExtension;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RRCReconfigurationSidelink_v1700_IEs_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RRCReconfigurationSidelink_v1700_IEs;
extern asn_SEQUENCE_specifics_t asn_SPC_RRCReconfigurationSidelink_v1700_IEs_specs_1;
extern asn_TYPE_member_t asn_MBR_RRCReconfigurationSidelink_v1700_IEs_1[5];

#ifdef __cplusplus
}
#endif

#endif	/* _RRCReconfigurationSidelink_v1700_IEs_H_ */
#include <asn_internal.h>
