/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "nr-rrc-17.3.0.asn1"
 * 	`asn1c -no-gen-BER -no-gen-OER -no-gen-XER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -S /home/amd/wrk/asn1c_oai/skeletons/`
 */

#ifndef	_RRCSetupComplete_v1690_IEs_H_
#define	_RRCSetupComplete_v1690_IEs_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum RRCSetupComplete_v1690_IEs__ul_RRC_Segmentation_r16 {
	RRCSetupComplete_v1690_IEs__ul_RRC_Segmentation_r16_true	= 0
} e_RRCSetupComplete_v1690_IEs__ul_RRC_Segmentation_r16;

/* Forward declarations */
struct RRCSetupComplete_v1700_IEs;

/* RRCSetupComplete-v1690-IEs */
typedef struct RRCSetupComplete_v1690_IEs {
	long	*ul_RRC_Segmentation_r16;	/* OPTIONAL */
	struct RRCSetupComplete_v1700_IEs	*nonCriticalExtension;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RRCSetupComplete_v1690_IEs_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_ul_RRC_Segmentation_r16_2;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_RRCSetupComplete_v1690_IEs;
extern asn_SEQUENCE_specifics_t asn_SPC_RRCSetupComplete_v1690_IEs_specs_1;
extern asn_TYPE_member_t asn_MBR_RRCSetupComplete_v1690_IEs_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _RRCSetupComplete_v1690_IEs_H_ */
#include <asn_internal.h>
