/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "PC5-RRC-Definitions"
 * 	found in "nr-rrc-17.3.0.asn1"
 * 	`asn1c -no-gen-BER -no-gen-OER -no-gen-XER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -S /home/amd/wrk/asn1c_oai/skeletons/`
 */

#ifndef	_SCCH_Message_H_
#define	_SCCH_Message_H_


#include <asn_application.h>

/* Including external dependencies */
#include "SCCH-MessageType.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SCCH-Message */
typedef struct SCCH_Message {
	SCCH_MessageType_t	 message;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SCCH_Message_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SCCH_Message;

#ifdef __cplusplus
}
#endif

#endif	/* _SCCH_Message_H_ */
#include <asn_internal.h>
