/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "nr-rrc-17.3.0.asn1"
 * 	`asn1c -no-gen-BER -no-gen-OER -no-gen-XER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -S /home/amd/wrk/asn1c_oai/skeletons/`
 */

#ifndef	_SCellConfig_H_
#define	_SCellConfig_H_


#include <asn_application.h>

/* Including external dependencies */
#include "SCellIndex.h"
#include <constr_SEQUENCE.h>
#include <NativeEnumerated.h>
#include <BIT_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum SCellConfig__ext2__sCellState_r16 {
	SCellConfig__ext2__sCellState_r16_activated	= 0
} e_SCellConfig__ext2__sCellState_r16;
typedef enum SCellConfig__ext2__secondaryDRX_GroupConfig_r16 {
	SCellConfig__ext2__secondaryDRX_GroupConfig_r16_true	= 0
} e_SCellConfig__ext2__secondaryDRX_GroupConfig_r16;

/* Forward declarations */
struct ServingCellConfigCommon;
struct ServingCellConfig;
struct SSB_MTC;
struct GoodServingCellEvaluation_r17;
struct SetupRelease_SCellSIB20_r17;

/* SCellConfig */
typedef struct SCellConfig {
	SCellIndex_t	 sCellIndex;
	struct ServingCellConfigCommon	*sCellConfigCommon;	/* OPTIONAL */
	struct ServingCellConfig	*sCellConfigDedicated;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	struct SCellConfig__ext1 {
		struct SSB_MTC	*smtc;	/* OPTIONAL */
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *ext1;
	struct SCellConfig__ext2 {
		long	*sCellState_r16;	/* OPTIONAL */
		long	*secondaryDRX_GroupConfig_r16;	/* OPTIONAL */
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *ext2;
	struct SCellConfig__ext3 {
		BIT_STRING_t	*preConfGapStatus_r17;	/* OPTIONAL */
		struct GoodServingCellEvaluation_r17	*goodServingCellEvaluationBFD_r17;	/* OPTIONAL */
		struct SetupRelease_SCellSIB20_r17	*sCellSIB20_r17;	/* OPTIONAL */
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *ext3;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SCellConfig_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_sCellState_r16_9;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_secondaryDRX_GroupConfig_r16_11;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_SCellConfig;
extern asn_SEQUENCE_specifics_t asn_SPC_SCellConfig_specs_1;
extern asn_TYPE_member_t asn_MBR_SCellConfig_1[6];

#ifdef __cplusplus
}
#endif

#endif	/* _SCellConfig_H_ */
#include <asn_internal.h>
