/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "nr-rrc-17.3.0.asn1"
 * 	`asn1c -no-gen-BER -no-gen-OER -no-gen-XER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -S /home/amd/wrk/asn1c_oai/skeletons/`
 */

#ifndef	_SDT_Config_r17_H_
#define	_SDT_Config_r17_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>
#include "DRB-Identity.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum SDT_Config_r17__sdt_SRB2_Indication_r17 {
	SDT_Config_r17__sdt_SRB2_Indication_r17_allowed	= 0
} e_SDT_Config_r17__sdt_SRB2_Indication_r17;
typedef enum SDT_Config_r17__sdt_DRB_ContinueROHC_r17 {
	SDT_Config_r17__sdt_DRB_ContinueROHC_r17_cell	= 0,
	SDT_Config_r17__sdt_DRB_ContinueROHC_r17_rna	= 1
} e_SDT_Config_r17__sdt_DRB_ContinueROHC_r17;

/* Forward declarations */
struct SetupRelease_SDT_CG_Config_r17;

/* SDT-Config-r17 */
typedef struct SDT_Config_r17 {
	struct SDT_Config_r17__sdt_DRB_List_r17 {
		A_SEQUENCE_OF(DRB_Identity_t) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *sdt_DRB_List_r17;
	long	*sdt_SRB2_Indication_r17;	/* OPTIONAL */
	struct SetupRelease_SDT_CG_Config_r17	*sdt_MAC_PHY_CG_Config_r17;	/* OPTIONAL */
	long	*sdt_DRB_ContinueROHC_r17;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SDT_Config_r17_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_sdt_SRB2_Indication_r17_4;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_sdt_DRB_ContinueROHC_r17_7;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_SDT_Config_r17;
extern asn_SEQUENCE_specifics_t asn_SPC_SDT_Config_r17_specs_1;
extern asn_TYPE_member_t asn_MBR_SDT_Config_r17_1[4];

#ifdef __cplusplus
}
#endif

#endif	/* _SDT_Config_r17_H_ */
#include <asn_internal.h>
