/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "nr-rrc-17.3.0.asn1"
 * 	`asn1c -no-gen-BER -no-gen-OER -no-gen-XER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -S /home/amd/wrk/asn1c_oai/skeletons/`
 */

#ifndef	_SharedSpectrumChAccessParamsPerBand_v1710_H_
#define	_SharedSpectrumChAccessParamsPerBand_v1710_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum SharedSpectrumChAccessParamsPerBand_v1710__ul_Semi_StaticChAccessDependentConfig_r17 {
	SharedSpectrumChAccessParamsPerBand_v1710__ul_Semi_StaticChAccessDependentConfig_r17_supported	= 0
} e_SharedSpectrumChAccessParamsPerBand_v1710__ul_Semi_StaticChAccessDependentConfig_r17;
typedef enum SharedSpectrumChAccessParamsPerBand_v1710__ul_Semi_StaticChAccessIndependentConfig_r17 {
	SharedSpectrumChAccessParamsPerBand_v1710__ul_Semi_StaticChAccessIndependentConfig_r17_supported	= 0
} e_SharedSpectrumChAccessParamsPerBand_v1710__ul_Semi_StaticChAccessIndependentConfig_r17;

/* SharedSpectrumChAccessParamsPerBand-v1710 */
typedef struct SharedSpectrumChAccessParamsPerBand_v1710 {
	long	*ul_Semi_StaticChAccessDependentConfig_r17;	/* OPTIONAL */
	long	*ul_Semi_StaticChAccessIndependentConfig_r17;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SharedSpectrumChAccessParamsPerBand_v1710_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_ul_Semi_StaticChAccessDependentConfig_r17_2;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_ul_Semi_StaticChAccessIndependentConfig_r17_4;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_SharedSpectrumChAccessParamsPerBand_v1710;
extern asn_SEQUENCE_specifics_t asn_SPC_SharedSpectrumChAccessParamsPerBand_v1710_specs_1;
extern asn_TYPE_member_t asn_MBR_SharedSpectrumChAccessParamsPerBand_v1710_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _SharedSpectrumChAccessParamsPerBand_v1710_H_ */
#include <asn_internal.h>
