/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "nr-rrc-17.3.0.asn1"
 * 	`asn1c -no-gen-BER -no-gen-OER -no-gen-XER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -S /home/amd/wrk/asn1c_oai/skeletons/`
 */

#ifndef	_SIB18_r17_H_
#define	_SIB18_r17_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct GIN_Element_r17;
struct GINs_PerSNPN_r17;

/* SIB18-r17 */
typedef struct SIB18_r17 {
	struct SIB18_r17__gin_ElementList_r17 {
		A_SEQUENCE_OF(struct GIN_Element_r17) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *gin_ElementList_r17;
	struct SIB18_r17__gins_PerSNPN_List_r17 {
		A_SEQUENCE_OF(struct GINs_PerSNPN_r17) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *gins_PerSNPN_List_r17;
	OCTET_STRING_t	*lateNonCriticalExtension;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SIB18_r17_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SIB18_r17;
extern asn_SEQUENCE_specifics_t asn_SPC_SIB18_r17_specs_1;
extern asn_TYPE_member_t asn_MBR_SIB18_r17_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _SIB18_r17_H_ */
#include <asn_internal.h>
