/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "nr-rrc-17.3.0.asn1"
 * 	`asn1c -no-gen-BER -no-gen-OER -no-gen-XER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -S /home/amd/wrk/asn1c_oai/skeletons/`
 */

#ifndef	_SIB3_H_
#define	_SIB3_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum SIB3__ext3__channelAccessMode2_r17 {
	SIB3__ext3__channelAccessMode2_r17_enabled	= 0
} e_SIB3__ext3__channelAccessMode2_r17;

/* Forward declarations */
struct IntraFreqNeighCellList;
struct IntraFreqExcludedCellList;
struct IntraFreqNeighCellList_v1610;
struct IntraFreqAllowedCellList_r16;
struct IntraFreqCAG_CellListPerPLMN_r16;
struct IntraFreqNeighHSDN_CellList_r17;
struct IntraFreqNeighCellList_v1710;

/* SIB3 */
typedef struct SIB3 {
	struct IntraFreqNeighCellList	*intraFreqNeighCellList;	/* OPTIONAL */
	struct IntraFreqExcludedCellList	*intraFreqExcludedCellList;	/* OPTIONAL */
	OCTET_STRING_t	*lateNonCriticalExtension;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	struct SIB3__ext1 {
		struct IntraFreqNeighCellList_v1610	*intraFreqNeighCellList_v1610;	/* OPTIONAL */
		struct IntraFreqAllowedCellList_r16	*intraFreqAllowedCellList_r16;	/* OPTIONAL */
		struct SIB3__ext1__intraFreqCAG_CellList_r16 {
			A_SEQUENCE_OF(struct IntraFreqCAG_CellListPerPLMN_r16) list;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} *intraFreqCAG_CellList_r16;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *ext1;
	struct SIB3__ext2 {
		struct IntraFreqNeighHSDN_CellList_r17	*intraFreqNeighHSDN_CellList_r17;	/* OPTIONAL */
		struct IntraFreqNeighCellList_v1710	*intraFreqNeighCellList_v1710;	/* OPTIONAL */
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *ext2;
	struct SIB3__ext3 {
		long	*channelAccessMode2_r17;	/* OPTIONAL */
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *ext3;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SIB3_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_channelAccessMode2_r17_15;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_SIB3;
extern asn_SEQUENCE_specifics_t asn_SPC_SIB3_specs_1;
extern asn_TYPE_member_t asn_MBR_SIB3_1[6];

#ifdef __cplusplus
}
#endif

#endif	/* _SIB3_H_ */
#include <asn_internal.h>
