/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "nr-rrc-17.3.0.asn1"
 * 	`asn1c -no-gen-BER -no-gen-OER -no-gen-XER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -S /home/amd/wrk/asn1c_oai/skeletons/`
 */

#ifndef	_SK_Counter_H_
#define	_SK_Counter_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SK-Counter */
typedef long	 SK_Counter_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_SK_Counter_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_SK_Counter;
asn_struct_free_f SK_Counter_free;
asn_struct_print_f SK_Counter_print;
asn_constr_check_f SK_Counter_constraint;
jer_type_encoder_f SK_Counter_encode_jer;
per_type_decoder_f SK_Counter_decode_uper;
per_type_encoder_f SK_Counter_encode_uper;
per_type_decoder_f SK_Counter_decode_aper;
per_type_encoder_f SK_Counter_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _SK_Counter_H_ */
#include <asn_internal.h>
