/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "nr-rrc-17.3.0.asn1"
 * 	`asn1c -no-gen-BER -no-gen-OER -no-gen-XER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -S /home/amd/wrk/asn1c_oai/skeletons/`
 */

#ifndef	_SL_BWP_DiscPoolConfig_r17_H_
#define	_SL_BWP_DiscPoolConfig_r17_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct SL_TxPoolDedicated_r16;
struct SL_ResourcePool_r16;

/* SL-BWP-DiscPoolConfig-r17 */
typedef struct SL_BWP_DiscPoolConfig_r17 {
	struct SL_BWP_DiscPoolConfig_r17__sl_DiscRxPool_r17 {
		A_SEQUENCE_OF(struct SL_ResourcePool_r16) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *sl_DiscRxPool_r17;
	struct SL_TxPoolDedicated_r16	*sl_DiscTxPoolSelected_r17;	/* OPTIONAL */
	struct SL_TxPoolDedicated_r16	*sl_DiscTxPoolScheduling_r17;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SL_BWP_DiscPoolConfig_r17_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SL_BWP_DiscPoolConfig_r17;
extern asn_SEQUENCE_specifics_t asn_SPC_SL_BWP_DiscPoolConfig_r17_specs_1;
extern asn_TYPE_member_t asn_MBR_SL_BWP_DiscPoolConfig_r17_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _SL_BWP_DiscPoolConfig_r17_H_ */
#include <asn_internal.h>
