/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "nr-rrc-17.3.0.asn1"
 * 	`asn1c -no-gen-BER -no-gen-OER -no-gen-XER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -S /home/amd/wrk/asn1c_oai/skeletons/`
 */

#ifndef	_SL_BWP_ConfigCommon_r16_H_
#define	_SL_BWP_ConfigCommon_r16_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct SL_BWP_Generic_r16;
struct SL_BWP_PoolConfigCommon_r16;
struct SL_BWP_DiscPoolConfigCommon_r17;

/* SL-BWP-ConfigCommon-r16 */
typedef struct SL_BWP_ConfigCommon_r16 {
	struct SL_BWP_Generic_r16	*sl_BWP_Generic_r16;	/* OPTIONAL */
	struct SL_BWP_PoolConfigCommon_r16	*sl_BWP_PoolConfigCommon_r16;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	struct SL_BWP_ConfigCommon_r16__ext1 {
		struct SL_BWP_PoolConfigCommon_r16	*sl_BWP_PoolConfigCommonPS_r17;	/* OPTIONAL */
		struct SL_BWP_DiscPoolConfigCommon_r17	*sl_BWP_DiscPoolConfigCommon_r17;	/* OPTIONAL */
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *ext1;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SL_BWP_ConfigCommon_r16_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SL_BWP_ConfigCommon_r16;
extern asn_SEQUENCE_specifics_t asn_SPC_SL_BWP_ConfigCommon_r16_specs_1;
extern asn_TYPE_member_t asn_MBR_SL_BWP_ConfigCommon_r16_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _SL_BWP_ConfigCommon_r16_H_ */
#include <asn_internal.h>
