/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "nr-rrc-17.3.0.asn1"
 * 	`asn1c -no-gen-BER -no-gen-OER -no-gen-XER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -S /home/amd/wrk/asn1c_oai/skeletons/`
 */

#ifndef	_SL_DRX_ConfigGC_BC_r17_H_
#define	_SL_DRX_ConfigGC_BC_r17_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct SL_DRX_GC_Generic_r17;
struct SL_DRX_GC_BC_QoS_r17;

/* SL-DRX-ConfigGC-BC-r17 */
typedef struct SL_DRX_ConfigGC_BC_r17 {
	struct SL_DRX_ConfigGC_BC_r17__sl_DRX_GC_BC_PerQoS_List_r17 {
		A_SEQUENCE_OF(struct SL_DRX_GC_BC_QoS_r17) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *sl_DRX_GC_BC_PerQoS_List_r17;
	struct SL_DRX_GC_Generic_r17	*sl_DRX_GC_generic_r17;	/* OPTIONAL */
	struct SL_DRX_GC_BC_QoS_r17	*sl_DefaultDRX_GC_BC_r17;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SL_DRX_ConfigGC_BC_r17_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SL_DRX_ConfigGC_BC_r17;
extern asn_SEQUENCE_specifics_t asn_SPC_SL_DRX_ConfigGC_BC_r17_specs_1;
extern asn_TYPE_member_t asn_MBR_SL_DRX_ConfigGC_BC_r17_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _SL_DRX_ConfigGC_BC_r17_H_ */
#include <asn_internal.h>
