/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "nr-rrc-17.3.0.asn1"
 * 	`asn1c -no-gen-BER -no-gen-OER -no-gen-XER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -S /home/amd/wrk/asn1c_oai/skeletons/`
 */

#ifndef	_SL_PriorityTxConfigIndex_v1650_H_
#define	_SL_PriorityTxConfigIndex_v1650_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct SL_MinMaxMCS_List_r16;

/* SL-PriorityTxConfigIndex-v1650 */
typedef struct SL_PriorityTxConfigIndex_v1650 {
	struct SL_PriorityTxConfigIndex_v1650__sl_MCS_RangeList_r16 {
		A_SEQUENCE_OF(struct SL_MinMaxMCS_List_r16) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *sl_MCS_RangeList_r16;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SL_PriorityTxConfigIndex_v1650_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SL_PriorityTxConfigIndex_v1650;
extern asn_SEQUENCE_specifics_t asn_SPC_SL_PriorityTxConfigIndex_v1650_specs_1;
extern asn_TYPE_member_t asn_MBR_SL_PriorityTxConfigIndex_v1650_1[1];

#ifdef __cplusplus
}
#endif

#endif	/* _SL_PriorityTxConfigIndex_v1650_H_ */
#include <asn_internal.h>
