/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-Sidelink-Preconf"
 * 	found in "nr-rrc-17.3.0.asn1"
 * 	`asn1c -no-gen-BER -no-gen-OER -no-gen-XER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -S /home/amd/wrk/asn1c_oai/skeletons/`
 */

#ifndef	_SL_PreconfigurationNR_r16_H_
#define	_SL_PreconfigurationNR_r16_H_


#include <asn_application.h>

/* Including external dependencies */
#include "SidelinkPreconfigNR-r16.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SL-PreconfigurationNR-r16 */
typedef struct SL_PreconfigurationNR_r16 {
	SidelinkPreconfigNR_r16_t	 sidelinkPreconfigNR_r16;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SL_PreconfigurationNR_r16_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SL_PreconfigurationNR_r16;

#ifdef __cplusplus
}
#endif

#endif	/* _SL_PreconfigurationNR_r16_H_ */
#include <asn_internal.h>
