/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "nr-rrc-17.3.0.asn1"
 * 	`asn1c -no-gen-BER -no-gen-OER -no-gen-XER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -S /home/amd/wrk/asn1c_oai/skeletons/`
 */

#ifndef	_SL_ReselectionConfig_r17_H_
#define	_SL_ReselectionConfig_r17_H_


#include <asn_application.h>

/* Including external dependencies */
#include "SL-RSRP-Range-r16.h"
#include "FilterCoefficient.h"
#include "Hysteresis.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SL-ReselectionConfig-r17 */
typedef struct SL_ReselectionConfig_r17 {
	SL_RSRP_Range_r16_t	*sl_RSRP_Thresh_r17;	/* OPTIONAL */
	FilterCoefficient_t	*sl_FilterCoefficientRSRP_r17;	/* OPTIONAL */
	Hysteresis_t	*sl_HystMin_r17;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SL_ReselectionConfig_r17_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SL_ReselectionConfig_r17;
extern asn_SEQUENCE_specifics_t asn_SPC_SL_ReselectionConfig_r17_specs_1;
extern asn_TYPE_member_t asn_MBR_SL_ReselectionConfig_r17_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _SL_ReselectionConfig_r17_H_ */
#include <asn_internal.h>
