/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "nr-rrc-17.3.0.asn1"
 * 	`asn1c -no-gen-BER -no-gen-OER -no-gen-XER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -S /home/amd/wrk/asn1c_oai/skeletons/`
 */

#ifndef	_SL_TxResourceReqCommRelay_r17_H_
#define	_SL_TxResourceReqCommRelay_r17_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum SL_TxResourceReqCommRelay_r17_PR {
	SL_TxResourceReqCommRelay_r17_PR_NOTHING,	/* No components present */
	SL_TxResourceReqCommRelay_r17_PR_sl_TxResourceReqL2U2N_Relay_r17,
	SL_TxResourceReqCommRelay_r17_PR_sl_TxResourceReqL3U2N_Relay_r17
} SL_TxResourceReqCommRelay_r17_PR;

/* Forward declarations */
struct SL_TxResourceReqL2U2N_Relay_r17;
struct SL_TxResourceReq_r16;

/* SL-TxResourceReqCommRelay-r17 */
typedef struct SL_TxResourceReqCommRelay_r17 {
	SL_TxResourceReqCommRelay_r17_PR present;
	union SL_TxResourceReqCommRelay_r17_u {
		struct SL_TxResourceReqL2U2N_Relay_r17	*sl_TxResourceReqL2U2N_Relay_r17;
		struct SL_TxResourceReq_r16	*sl_TxResourceReqL3U2N_Relay_r17;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SL_TxResourceReqCommRelay_r17_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SL_TxResourceReqCommRelay_r17;
extern asn_CHOICE_specifics_t asn_SPC_SL_TxResourceReqCommRelay_r17_specs_1;
extern asn_TYPE_member_t asn_MBR_SL_TxResourceReqCommRelay_r17_1[2];
extern asn_per_constraints_t asn_PER_type_SL_TxResourceReqCommRelay_r17_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _SL_TxResourceReqCommRelay_r17_H_ */
#include <asn_internal.h>
