/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "nr-rrc-17.3.0.asn1"
 * 	`asn1c -no-gen-BER -no-gen-OER -no-gen-XER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -S /home/amd/wrk/asn1c_oai/skeletons/`
 */

#ifndef	_SliceCellListNR_r17_H_
#define	_SliceCellListNR_r17_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct PCI_Range;

/* SliceCellListNR-r17 */
typedef struct SliceCellListNR_r17 {
	A_SEQUENCE_OF(struct PCI_Range) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SliceCellListNR_r17_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SliceCellListNR_r17;
extern asn_SET_OF_specifics_t asn_SPC_SliceCellListNR_r17_specs_1;
extern asn_TYPE_member_t asn_MBR_SliceCellListNR_r17_1[1];
extern asn_per_constraints_t asn_PER_type_SliceCellListNR_r17_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _SliceCellListNR_r17_H_ */
#include <asn_internal.h>
