/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "nr-rrc-17.3.0.asn1"
 * 	`asn1c -no-gen-BER -no-gen-OER -no-gen-XER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -S /home/amd/wrk/asn1c_oai/skeletons/`
 */

#ifndef	_SRB_ToAddMod_H_
#define	_SRB_ToAddMod_H_


#include <asn_application.h>

/* Including external dependencies */
#include "SRB-Identity.h"
#include <NativeEnumerated.h>
#include "SRB-Identity-v1700.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum SRB_ToAddMod__reestablishPDCP {
	SRB_ToAddMod__reestablishPDCP_true	= 0
} e_SRB_ToAddMod__reestablishPDCP;
typedef enum SRB_ToAddMod__discardOnPDCP {
	SRB_ToAddMod__discardOnPDCP_true	= 0
} e_SRB_ToAddMod__discardOnPDCP;

/* Forward declarations */
struct PDCP_Config;

/* SRB-ToAddMod */
typedef struct SRB_ToAddMod {
	SRB_Identity_t	 srb_Identity;
	long	*reestablishPDCP;	/* OPTIONAL */
	long	*discardOnPDCP;	/* OPTIONAL */
	struct PDCP_Config	*pdcp_Config;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	struct SRB_ToAddMod__ext1 {
		SRB_Identity_v1700_t	*srb_Identity_v1700;	/* OPTIONAL */
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *ext1;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SRB_ToAddMod_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_reestablishPDCP_3;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_discardOnPDCP_5;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_SRB_ToAddMod;
extern asn_SEQUENCE_specifics_t asn_SPC_SRB_ToAddMod_specs_1;
extern asn_TYPE_member_t asn_MBR_SRB_ToAddMod_1[5];

#ifdef __cplusplus
}
#endif

#endif	/* _SRB_ToAddMod_H_ */
#include <asn_internal.h>
