/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "nr-rrc-17.3.0.asn1"
 * 	`asn1c -no-gen-BER -no-gen-OER -no-gen-XER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -S /home/amd/wrk/asn1c_oai/skeletons/`
 */

#ifndef	_SRS_PosConfig_r17_H_
#define	_SRS_PosConfig_r17_H_


#include <asn_application.h>

/* Including external dependencies */
#include "SRS-PosResourceSetId-r16.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include "SRS-PosResourceId-r16.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct SRS_PosResourceSet_r16;
struct SRS_PosResource_r16;

/* SRS-PosConfig-r17 */
typedef struct SRS_PosConfig_r17 {
	struct SRS_PosConfig_r17__srs_PosResourceSetToReleaseList_r17 {
		A_SEQUENCE_OF(SRS_PosResourceSetId_r16_t) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *srs_PosResourceSetToReleaseList_r17;
	struct SRS_PosConfig_r17__srs_PosResourceSetToAddModList_r17 {
		A_SEQUENCE_OF(struct SRS_PosResourceSet_r16) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *srs_PosResourceSetToAddModList_r17;
	struct SRS_PosConfig_r17__srs_PosResourceToReleaseList_r17 {
		A_SEQUENCE_OF(SRS_PosResourceId_r16_t) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *srs_PosResourceToReleaseList_r17;
	struct SRS_PosConfig_r17__srs_PosResourceToAddModList_r17 {
		A_SEQUENCE_OF(struct SRS_PosResource_r16) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *srs_PosResourceToAddModList_r17;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SRS_PosConfig_r17_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SRS_PosConfig_r17;
extern asn_SEQUENCE_specifics_t asn_SPC_SRS_PosConfig_r17_specs_1;
extern asn_TYPE_member_t asn_MBR_SRS_PosConfig_r17_1[4];

#ifdef __cplusplus
}
#endif

#endif	/* _SRS_PosConfig_r17_H_ */
#include <asn_internal.h>
