/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "nr-rrc-17.3.0.asn1"
 * 	`asn1c -no-gen-BER -no-gen-OER -no-gen-XER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -S /home/amd/wrk/asn1c_oai/skeletons/`
 */

#ifndef	_SRS_AllPosResources_r16_H_
#define	_SRS_AllPosResources_r16_H_


#include <asn_application.h>

/* Including external dependencies */
#include "SRS-PosResources-r16.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct SRS_PosResourceAP_r16;
struct SRS_PosResourceSP_r16;

/* SRS-AllPosResources-r16 */
typedef struct SRS_AllPosResources_r16 {
	SRS_PosResources_r16_t	 srs_PosResources_r16;
	struct SRS_PosResourceAP_r16	*srs_PosResourceAP_r16;	/* OPTIONAL */
	struct SRS_PosResourceSP_r16	*srs_PosResourceSP_r16;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SRS_AllPosResources_r16_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SRS_AllPosResources_r16;
extern asn_SEQUENCE_specifics_t asn_SPC_SRS_AllPosResources_r16_specs_1;
extern asn_TYPE_member_t asn_MBR_SRS_AllPosResources_r16_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _SRS_AllPosResources_r16_H_ */
#include <asn_internal.h>
