/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "nr-rrc-17.3.0.asn1"
 * 	`asn1c -no-gen-BER -no-gen-OER -no-gen-XER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -S /home/amd/wrk/asn1c_oai/skeletons/`
 */

#ifndef	_SSB_InfoNcell_r16_H_
#define	_SSB_InfoNcell_r16_H_


#include <asn_application.h>

/* Including external dependencies */
#include "PhysCellId.h"
#include "SSB-Index.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct SSB_Configuration_r16;

/* SSB-InfoNcell-r16 */
typedef struct SSB_InfoNcell_r16 {
	PhysCellId_t	 physicalCellId_r16;
	SSB_Index_t	*ssb_IndexNcell_r16;	/* OPTIONAL */
	struct SSB_Configuration_r16	*ssb_Configuration_r16;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SSB_InfoNcell_r16_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SSB_InfoNcell_r16;
extern asn_SEQUENCE_specifics_t asn_SPC_SSB_InfoNcell_r16_specs_1;
extern asn_TYPE_member_t asn_MBR_SSB_InfoNcell_r16_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _SSB_InfoNcell_r16_H_ */
#include <asn_internal.h>
