/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "nr-rrc-17.3.0.asn1"
 * 	`asn1c -no-gen-BER -no-gen-OER -no-gen-XER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -S /home/amd/wrk/asn1c_oai/skeletons/`
 */

#ifndef	_SubcarrierSpacing_H_
#define	_SubcarrierSpacing_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum SubcarrierSpacing {
	SubcarrierSpacing_kHz15	= 0,
	SubcarrierSpacing_kHz30	= 1,
	SubcarrierSpacing_kHz60	= 2,
	SubcarrierSpacing_kHz120	= 3,
	SubcarrierSpacing_kHz240	= 4,
	SubcarrierSpacing_kHz480_v1700	= 5,
	SubcarrierSpacing_kHz960_v1700	= 6,
	SubcarrierSpacing_spare1	= 7
} e_SubcarrierSpacing;

/* SubcarrierSpacing */
typedef long	 SubcarrierSpacing_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_SubcarrierSpacing_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_SubcarrierSpacing;
extern const asn_INTEGER_specifics_t asn_SPC_SubcarrierSpacing_specs_1;
asn_struct_free_f SubcarrierSpacing_free;
asn_struct_print_f SubcarrierSpacing_print;
asn_constr_check_f SubcarrierSpacing_constraint;
jer_type_encoder_f SubcarrierSpacing_encode_jer;
per_type_decoder_f SubcarrierSpacing_decode_uper;
per_type_encoder_f SubcarrierSpacing_encode_uper;
per_type_decoder_f SubcarrierSpacing_decode_aper;
per_type_encoder_f SubcarrierSpacing_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _SubcarrierSpacing_H_ */
#include <asn_internal.h>
