/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "nr-rrc-17.3.0.asn1"
 * 	`asn1c -no-gen-BER -no-gen-OER -no-gen-XER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -S /home/amd/wrk/asn1c_oai/skeletons/`
 */

#ifndef	_SystemInformation_IEs_H_
#define	_SystemInformation_IEs_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>
#include <asn_SEQUENCE_OF.h>
#include <constr_CHOICE.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum SystemInformation_IEs__sib_TypeAndInfo__Member_PR {
	SystemInformation_IEs__sib_TypeAndInfo__Member_PR_NOTHING,	/* No components present */
	SystemInformation_IEs__sib_TypeAndInfo__Member_PR_sib2,
	SystemInformation_IEs__sib_TypeAndInfo__Member_PR_sib3,
	SystemInformation_IEs__sib_TypeAndInfo__Member_PR_sib4,
	SystemInformation_IEs__sib_TypeAndInfo__Member_PR_sib5,
	SystemInformation_IEs__sib_TypeAndInfo__Member_PR_sib6,
	SystemInformation_IEs__sib_TypeAndInfo__Member_PR_sib7,
	SystemInformation_IEs__sib_TypeAndInfo__Member_PR_sib8,
	SystemInformation_IEs__sib_TypeAndInfo__Member_PR_sib9,
	/* Extensions may appear below */
	SystemInformation_IEs__sib_TypeAndInfo__Member_PR_sib10_v1610,
	SystemInformation_IEs__sib_TypeAndInfo__Member_PR_sib11_v1610,
	SystemInformation_IEs__sib_TypeAndInfo__Member_PR_sib12_v1610,
	SystemInformation_IEs__sib_TypeAndInfo__Member_PR_sib13_v1610,
	SystemInformation_IEs__sib_TypeAndInfo__Member_PR_sib14_v1610,
	SystemInformation_IEs__sib_TypeAndInfo__Member_PR_sib15_v1700,
	SystemInformation_IEs__sib_TypeAndInfo__Member_PR_sib16_v1700,
	SystemInformation_IEs__sib_TypeAndInfo__Member_PR_sib17_v1700,
	SystemInformation_IEs__sib_TypeAndInfo__Member_PR_sib18_v1700,
	SystemInformation_IEs__sib_TypeAndInfo__Member_PR_sib19_v1700,
	SystemInformation_IEs__sib_TypeAndInfo__Member_PR_sib20_v1700,
	SystemInformation_IEs__sib_TypeAndInfo__Member_PR_sib21_v1700
} SystemInformation_IEs__sib_TypeAndInfo__Member_PR;

/* Forward declarations */
struct SIB2;
struct SIB3;
struct SIB4;
struct SIB5;
struct SIB6;
struct SIB7;
struct SIB8;
struct SIB9;
struct SIB10_r16;
struct SIB11_r16;
struct SIB12_r16;
struct SIB13_r16;
struct SIB14_r16;
struct SIB15_r17;
struct SIB16_r17;
struct SIB17_r17;
struct SIB18_r17;
struct SIB19_r17;
struct SIB20_r17;
struct SIB21_r17;

/* Forward definitions */
typedef struct SystemInformation_IEs__sib_TypeAndInfo__Member {
	SystemInformation_IEs__sib_TypeAndInfo__Member_PR present;
	union SystemInformation_IEs__sib_TypeAndInfo__Member_u {
		struct SIB2	*sib2;
		struct SIB3	*sib3;
		struct SIB4	*sib4;
		struct SIB5	*sib5;
		struct SIB6	*sib6;
		struct SIB7	*sib7;
		struct SIB8	*sib8;
		struct SIB9	*sib9;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
		struct SIB10_r16	*sib10_v1610;
		struct SIB11_r16	*sib11_v1610;
		struct SIB12_r16	*sib12_v1610;
		struct SIB13_r16	*sib13_v1610;
		struct SIB14_r16	*sib14_v1610;
		struct SIB15_r17	*sib15_v1700;
		struct SIB16_r17	*sib16_v1700;
		struct SIB17_r17	*sib17_v1700;
		struct SIB18_r17	*sib18_v1700;
		struct SIB19_r17	*sib19_v1700;
		struct SIB20_r17	*sib20_v1700;
		struct SIB21_r17	*sib21_v1700;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SystemInformation_IEs__sib_TypeAndInfo__Member;

/* SystemInformation-IEs */
typedef struct SystemInformation_IEs {
	struct SystemInformation_IEs__sib_TypeAndInfo {
		A_SEQUENCE_OF(SystemInformation_IEs__sib_TypeAndInfo__Member) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} sib_TypeAndInfo;
	OCTET_STRING_t	*lateNonCriticalExtension;	/* OPTIONAL */
	struct SystemInformation_IEs__nonCriticalExtension {
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *nonCriticalExtension;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SystemInformation_IEs_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SystemInformation_IEs;
extern asn_SEQUENCE_specifics_t asn_SPC_SystemInformation_IEs_specs_1;
extern asn_TYPE_member_t asn_MBR_SystemInformation_IEs_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _SystemInformation_IEs_H_ */
#include <asn_internal.h>
