/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "nr-rrc-17.3.0.asn1"
 * 	`asn1c -no-gen-BER -no-gen-OER -no-gen-XER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -S /home/amd/wrk/asn1c_oai/skeletons/`
 */

#ifndef	_T_ReassemblyExt_r17_H_
#define	_T_ReassemblyExt_r17_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum T_ReassemblyExt_r17 {
	T_ReassemblyExt_r17_ms210	= 0,
	T_ReassemblyExt_r17_ms220	= 1,
	T_ReassemblyExt_r17_ms340	= 2,
	T_ReassemblyExt_r17_ms350	= 3,
	T_ReassemblyExt_r17_ms550	= 4,
	T_ReassemblyExt_r17_ms1100	= 5,
	T_ReassemblyExt_r17_ms1650	= 6,
	T_ReassemblyExt_r17_ms2200	= 7
} e_T_ReassemblyExt_r17;

/* T-ReassemblyExt-r17 */
typedef long	 T_ReassemblyExt_r17_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_T_ReassemblyExt_r17_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_T_ReassemblyExt_r17;
extern const asn_INTEGER_specifics_t asn_SPC_T_ReassemblyExt_r17_specs_1;
asn_struct_free_f T_ReassemblyExt_r17_free;
asn_struct_print_f T_ReassemblyExt_r17_print;
asn_constr_check_f T_ReassemblyExt_r17_constraint;
jer_type_encoder_f T_ReassemblyExt_r17_encode_jer;
per_type_decoder_f T_ReassemblyExt_r17_decode_uper;
per_type_encoder_f T_ReassemblyExt_r17_encode_uper;
per_type_decoder_f T_ReassemblyExt_r17_decode_aper;
per_type_encoder_f T_ReassemblyExt_r17_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _T_ReassemblyExt_r17_H_ */
#include <asn_internal.h>
