/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "nr-rrc-17.3.0.asn1"
 * 	`asn1c -no-gen-BER -no-gen-OER -no-gen-XER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -S /home/amd/wrk/asn1c_oai/skeletons/`
 */

#ifndef	_TwoPUCCH_Grp_Configurations_r16_H_
#define	_TwoPUCCH_Grp_Configurations_r16_H_


#include <asn_application.h>

/* Including external dependencies */
#include "TwoPUCCH-Grp-ConfigParams-r16.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* TwoPUCCH-Grp-Configurations-r16 */
typedef struct TwoPUCCH_Grp_Configurations_r16 {
	TwoPUCCH_Grp_ConfigParams_r16_t	 pucch_PrimaryGroupMapping_r16;
	TwoPUCCH_Grp_ConfigParams_r16_t	 pucch_SecondaryGroupMapping_r16;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} TwoPUCCH_Grp_Configurations_r16_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TwoPUCCH_Grp_Configurations_r16;
extern asn_SEQUENCE_specifics_t asn_SPC_TwoPUCCH_Grp_Configurations_r16_specs_1;
extern asn_TYPE_member_t asn_MBR_TwoPUCCH_Grp_Configurations_r16_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _TwoPUCCH_Grp_Configurations_r16_H_ */
#include <asn_internal.h>
