/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "nr-rrc-17.3.0.asn1"
 * 	`asn1c -no-gen-BER -no-gen-OER -no-gen-XER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -S /home/amd/wrk/asn1c_oai/skeletons/`
 */

#ifndef	_UE_CapabilityRequestFilterNR_v1540_H_
#define	_UE_CapabilityRequestFilterNR_v1540_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum UE_CapabilityRequestFilterNR_v1540__srs_SwitchingTimeRequest {
	UE_CapabilityRequestFilterNR_v1540__srs_SwitchingTimeRequest_true	= 0
} e_UE_CapabilityRequestFilterNR_v1540__srs_SwitchingTimeRequest;

/* Forward declarations */
struct UE_CapabilityRequestFilterNR_v1710;

/* UE-CapabilityRequestFilterNR-v1540 */
typedef struct UE_CapabilityRequestFilterNR_v1540 {
	long	*srs_SwitchingTimeRequest;	/* OPTIONAL */
	struct UE_CapabilityRequestFilterNR_v1710	*nonCriticalExtension;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} UE_CapabilityRequestFilterNR_v1540_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_srs_SwitchingTimeRequest_2;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_UE_CapabilityRequestFilterNR_v1540;
extern asn_SEQUENCE_specifics_t asn_SPC_UE_CapabilityRequestFilterNR_v1540_specs_1;
extern asn_TYPE_member_t asn_MBR_UE_CapabilityRequestFilterNR_v1540_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _UE_CapabilityRequestFilterNR_v1540_H_ */
#include <asn_internal.h>
