/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "nr-rrc-17.3.0.asn1"
 * 	`asn1c -no-gen-BER -no-gen-OER -no-gen-XER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -S /home/amd/wrk/asn1c_oai/skeletons/`
 */

#ifndef	_UE_MRDC_Capability_v1730_H_
#define	_UE_MRDC_Capability_v1730_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct MeasAndMobParametersMRDC_v1730;

/* UE-MRDC-Capability-v1730 */
typedef struct UE_MRDC_Capability_v1730 {
	struct MeasAndMobParametersMRDC_v1730	*measAndMobParametersMRDC_v1730;	/* OPTIONAL */
	struct UE_MRDC_Capability_v1730__nonCriticalExtension {
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *nonCriticalExtension;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} UE_MRDC_Capability_v1730_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UE_MRDC_Capability_v1730;
extern asn_SEQUENCE_specifics_t asn_SPC_UE_MRDC_Capability_v1730_specs_1;
extern asn_TYPE_member_t asn_MBR_UE_MRDC_Capability_v1730_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _UE_MRDC_Capability_v1730_H_ */
#include <asn_internal.h>
