/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "nr-rrc-17.3.0.asn1"
 * 	`asn1c -no-gen-BER -no-gen-OER -no-gen-XER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -S /home/amd/wrk/asn1c_oai/skeletons/`
 */

#ifndef	_UEAssistanceInformation_v1610_IEs_H_
#define	_UEAssistanceInformation_v1610_IEs_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BOOLEAN.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct IDC_Assistance_r16;
struct DRX_Preference_r16;
struct MaxBW_Preference_r16;
struct MaxCC_Preference_r16;
struct MaxMIMO_LayerPreference_r16;
struct MinSchedulingOffsetPreference_r16;
struct ReleasePreference_r16;
struct SL_UE_AssistanceInformationNR_r16;
struct UEAssistanceInformation_v1700_IEs;

/* UEAssistanceInformation-v1610-IEs */
typedef struct UEAssistanceInformation_v1610_IEs {
	struct IDC_Assistance_r16	*idc_Assistance_r16;	/* OPTIONAL */
	struct DRX_Preference_r16	*drx_Preference_r16;	/* OPTIONAL */
	struct MaxBW_Preference_r16	*maxBW_Preference_r16;	/* OPTIONAL */
	struct MaxCC_Preference_r16	*maxCC_Preference_r16;	/* OPTIONAL */
	struct MaxMIMO_LayerPreference_r16	*maxMIMO_LayerPreference_r16;	/* OPTIONAL */
	struct MinSchedulingOffsetPreference_r16	*minSchedulingOffsetPreference_r16;	/* OPTIONAL */
	struct ReleasePreference_r16	*releasePreference_r16;	/* OPTIONAL */
	struct SL_UE_AssistanceInformationNR_r16	*sl_UE_AssistanceInformationNR_r16;	/* OPTIONAL */
	BOOLEAN_t	*referenceTimeInfoPreference_r16;	/* OPTIONAL */
	struct UEAssistanceInformation_v1700_IEs	*nonCriticalExtension;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} UEAssistanceInformation_v1610_IEs_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UEAssistanceInformation_v1610_IEs;
extern asn_SEQUENCE_specifics_t asn_SPC_UEAssistanceInformation_v1610_IEs_specs_1;
extern asn_TYPE_member_t asn_MBR_UEAssistanceInformation_v1610_IEs_1[10];

#ifdef __cplusplus
}
#endif

#endif	/* _UEAssistanceInformation_v1610_IEs_H_ */
#include <asn_internal.h>
