/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "PC5-RRC-Definitions"
 * 	found in "nr-rrc-17.3.0.asn1"
 * 	`asn1c -no-gen-BER -no-gen-OER -no-gen-XER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -S /home/amd/wrk/asn1c_oai/skeletons/`
 */

#ifndef	_UEAssistanceInformationSidelink_r17_H_
#define	_UEAssistanceInformationSidelink_r17_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_SEQUENCE.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum UEAssistanceInformationSidelink_r17__criticalExtensions_PR {
	UEAssistanceInformationSidelink_r17__criticalExtensions_PR_NOTHING,	/* No components present */
	UEAssistanceInformationSidelink_r17__criticalExtensions_PR_ueAssistanceInformationSidelink_r17,
	UEAssistanceInformationSidelink_r17__criticalExtensions_PR_criticalExtensionsFuture
} UEAssistanceInformationSidelink_r17__criticalExtensions_PR;

/* Forward declarations */
struct UEAssistanceInformationSidelink_r17_IEs;

/* UEAssistanceInformationSidelink-r17 */
typedef struct UEAssistanceInformationSidelink_r17 {
	struct UEAssistanceInformationSidelink_r17__criticalExtensions {
		UEAssistanceInformationSidelink_r17__criticalExtensions_PR present;
		union UEAssistanceInformationSidelink_r17__criticalExtensions_u {
			struct UEAssistanceInformationSidelink_r17_IEs	*ueAssistanceInformationSidelink_r17;
			struct UEAssistanceInformationSidelink_r17__criticalExtensions__criticalExtensionsFuture {
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} *criticalExtensionsFuture;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} criticalExtensions;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} UEAssistanceInformationSidelink_r17_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UEAssistanceInformationSidelink_r17;
extern asn_SEQUENCE_specifics_t asn_SPC_UEAssistanceInformationSidelink_r17_specs_1;
extern asn_TYPE_member_t asn_MBR_UEAssistanceInformationSidelink_r17_1[1];

#ifdef __cplusplus
}
#endif

#endif	/* _UEAssistanceInformationSidelink_r17_H_ */
#include <asn_internal.h>
