/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "nr-rrc-17.3.0.asn1"
 * 	`asn1c -no-gen-BER -no-gen-OER -no-gen-XER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -S /home/amd/wrk/asn1c_oai/skeletons/`
 */

#ifndef	_UECapabilityEnquiry_v1560_IEs_H_
#define	_UECapabilityEnquiry_v1560_IEs_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct UE_CapabilityRequestFilterCommon;
struct UECapabilityEnquiry_v1610_IEs;

/* UECapabilityEnquiry-v1560-IEs */
typedef struct UECapabilityEnquiry_v1560_IEs {
	struct UE_CapabilityRequestFilterCommon	*capabilityRequestFilterCommon;	/* OPTIONAL */
	struct UECapabilityEnquiry_v1610_IEs	*nonCriticalExtension;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} UECapabilityEnquiry_v1560_IEs_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UECapabilityEnquiry_v1560_IEs;

#ifdef __cplusplus
}
#endif

#endif	/* _UECapabilityEnquiry_v1560_IEs_H_ */
#include <asn_internal.h>
