/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "PC5-RRC-Definitions"
 * 	found in "nr-rrc-17.3.0.asn1"
 * 	`asn1c -no-gen-BER -no-gen-OER -no-gen-XER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -S /home/amd/wrk/asn1c_oai/skeletons/`
 */

#ifndef	_UECapabilityEnquirySidelink_r16_IEs_H_
#define	_UECapabilityEnquirySidelink_r16_IEs_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct FreqBandList;

/* UECapabilityEnquirySidelink-r16-IEs */
typedef struct UECapabilityEnquirySidelink_r16_IEs {
	struct FreqBandList	*frequencyBandListFilterSidelink_r16;	/* OPTIONAL */
	OCTET_STRING_t	*ue_CapabilityInformationSidelink_r16;	/* OPTIONAL */
	OCTET_STRING_t	*lateNonCriticalExtension;	/* OPTIONAL */
	struct UECapabilityEnquirySidelink_r16_IEs__nonCriticalExtension {
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *nonCriticalExtension;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} UECapabilityEnquirySidelink_r16_IEs_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UECapabilityEnquirySidelink_r16_IEs;
extern asn_SEQUENCE_specifics_t asn_SPC_UECapabilityEnquirySidelink_r16_IEs_specs_1;
extern asn_TYPE_member_t asn_MBR_UECapabilityEnquirySidelink_r16_IEs_1[4];

#ifdef __cplusplus
}
#endif

#endif	/* _UECapabilityEnquirySidelink_r16_IEs_H_ */
#include <asn_internal.h>
