/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "nr-rrc-17.3.0.asn1"
 * 	`asn1c -no-gen-BER -no-gen-OER -no-gen-XER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -S /home/amd/wrk/asn1c_oai/skeletons/`
 */

#ifndef	_UEInformationResponse_v1700_IEs_H_
#define	_UEInformationResponse_v1700_IEs_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct SuccessHO_Report_r17;
struct ConnEstFailReportList_r17;

/* UEInformationResponse-v1700-IEs */
typedef struct UEInformationResponse_v1700_IEs {
	struct SuccessHO_Report_r17	*successHO_Report_r17;	/* OPTIONAL */
	struct ConnEstFailReportList_r17	*connEstFailReportList_r17;	/* OPTIONAL */
	OCTET_STRING_t	*coarseLocationInfo_r17;	/* OPTIONAL */
	struct UEInformationResponse_v1700_IEs__nonCriticalExtension {
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *nonCriticalExtension;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} UEInformationResponse_v1700_IEs_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UEInformationResponse_v1700_IEs;
extern asn_SEQUENCE_specifics_t asn_SPC_UEInformationResponse_v1700_IEs_specs_1;
extern asn_TYPE_member_t asn_MBR_UEInformationResponse_v1700_IEs_1[4];

#ifdef __cplusplus
}
#endif

#endif	/* _UEInformationResponse_v1700_IEs_H_ */
#include <asn_internal.h>
