/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "nr-rrc-17.3.0.asn1"
 * 	`asn1c -no-gen-BER -no-gen-OER -no-gen-XER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -S /home/amd/wrk/asn1c_oai/skeletons/`
 */

#ifndef	_UEInformationResponse_r16_IEs_H_
#define	_UEInformationResponse_r16_IEs_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct MeasResultIdleEUTRA_r16;
struct MeasResultIdleNR_r16;
struct LogMeasReport_r16;
struct ConnEstFailReport_r16;
struct RA_ReportList_r16;
struct RLF_Report_r16;
struct MobilityHistoryReport_r16;
struct UEInformationResponse_v1700_IEs;

/* UEInformationResponse-r16-IEs */
typedef struct UEInformationResponse_r16_IEs {
	struct MeasResultIdleEUTRA_r16	*measResultIdleEUTRA_r16;	/* OPTIONAL */
	struct MeasResultIdleNR_r16	*measResultIdleNR_r16;	/* OPTIONAL */
	struct LogMeasReport_r16	*logMeasReport_r16;	/* OPTIONAL */
	struct ConnEstFailReport_r16	*connEstFailReport_r16;	/* OPTIONAL */
	struct RA_ReportList_r16	*ra_ReportList_r16;	/* OPTIONAL */
	struct RLF_Report_r16	*rlf_Report_r16;	/* OPTIONAL */
	struct MobilityHistoryReport_r16	*mobilityHistoryReport_r16;	/* OPTIONAL */
	OCTET_STRING_t	*lateNonCriticalExtension;	/* OPTIONAL */
	struct UEInformationResponse_v1700_IEs	*nonCriticalExtension;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} UEInformationResponse_r16_IEs_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UEInformationResponse_r16_IEs;
extern asn_SEQUENCE_specifics_t asn_SPC_UEInformationResponse_r16_IEs_specs_1;
extern asn_TYPE_member_t asn_MBR_UEInformationResponse_r16_IEs_1[9];

#ifdef __cplusplus
}
#endif

#endif	/* _UEInformationResponse_r16_IEs_H_ */
#include <asn_internal.h>
