/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "nr-rrc-17.3.0.asn1"
 * 	`asn1c -no-gen-BER -no-gen-OER -no-gen-XER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -S /home/amd/wrk/asn1c_oai/skeletons/`
 */

#ifndef	_ULInformationTransfer_v1700_IEs_H_
#define	_ULInformationTransfer_v1700_IEs_H_


#include <asn_application.h>

/* Including external dependencies */
#include "DedicatedInfoF1c-r17.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ULInformationTransfer-v1700-IEs */
typedef struct ULInformationTransfer_v1700_IEs {
	DedicatedInfoF1c_r17_t	*dedicatedInfoF1c_r17;	/* OPTIONAL */
	struct ULInformationTransfer_v1700_IEs__nonCriticalExtension {
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *nonCriticalExtension;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ULInformationTransfer_v1700_IEs_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ULInformationTransfer_v1700_IEs;
extern asn_SEQUENCE_specifics_t asn_SPC_ULInformationTransfer_v1700_IEs_specs_1;
extern asn_TYPE_member_t asn_MBR_ULInformationTransfer_v1700_IEs_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _ULInformationTransfer_v1700_IEs_H_ */
#include <asn_internal.h>
