/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "nr-rrc-17.3.0.asn1"
 * 	`asn1c -no-gen-BER -no-gen-OER -no-gen-XER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -S /home/amd/wrk/asn1c_oai/skeletons/`
 */

#ifndef	_UplinkTxDirectCurrentTwoCarrier_r16_H_
#define	_UplinkTxDirectCurrentTwoCarrier_r16_H_


#include <asn_application.h>

/* Including external dependencies */
#include "UplinkTxDirectCurrentCarrierInfo-r16.h"
#include "UplinkTxDirectCurrentTwoCarrierInfo-r16.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct UplinkTxDirectCurrentTwoCarrierInfo_r16;

/* UplinkTxDirectCurrentTwoCarrier-r16 */
typedef struct UplinkTxDirectCurrentTwoCarrier_r16 {
	UplinkTxDirectCurrentCarrierInfo_r16_t	 carrierOneInfo_r16;
	UplinkTxDirectCurrentCarrierInfo_r16_t	 carrierTwoInfo_r16;
	UplinkTxDirectCurrentTwoCarrierInfo_r16_t	 singlePA_TxDirectCurrent_r16;
	struct UplinkTxDirectCurrentTwoCarrierInfo_r16	*secondPA_TxDirectCurrent_r16;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} UplinkTxDirectCurrentTwoCarrier_r16_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UplinkTxDirectCurrentTwoCarrier_r16;
extern asn_SEQUENCE_specifics_t asn_SPC_UplinkTxDirectCurrentTwoCarrier_r16_specs_1;
extern asn_TYPE_member_t asn_MBR_UplinkTxDirectCurrentTwoCarrier_r16_1[4];

#ifdef __cplusplus
}
#endif

#endif	/* _UplinkTxDirectCurrentTwoCarrier_r16_H_ */
#include <asn_internal.h>
