/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-UE-Variables"
 * 	found in "nr-rrc-17.3.0.asn1"
 * 	`asn1c -no-gen-BER -no-gen-OER -no-gen-XER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -S /home/amd/wrk/asn1c_oai/skeletons/`
 */

#ifndef	_VarConnEstFailReportList_r17_H_
#define	_VarConnEstFailReportList_r17_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct VarConnEstFailReport_r16;

/* VarConnEstFailReportList-r17 */
typedef struct VarConnEstFailReportList_r17 {
	struct VarConnEstFailReportList_r17__connEstFailReportList_r17 {
		A_SEQUENCE_OF(struct VarConnEstFailReport_r16) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} connEstFailReportList_r17;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} VarConnEstFailReportList_r17_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_VarConnEstFailReportList_r17;

#ifdef __cplusplus
}
#endif

#endif	/* _VarConnEstFailReportList_r17_H_ */
#include <asn_internal.h>
