/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-UE-Variables"
 * 	found in "nr-rrc-17.3.0.asn1"
 * 	`asn1c -no-gen-BER -no-gen-OER -no-gen-XER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -S /home/amd/wrk/asn1c_oai/skeletons/`
 */

#ifndef	_VarMeasIdleReport_r16_H_
#define	_VarMeasIdleReport_r16_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct MeasResultIdleNR_r16;
struct MeasResultIdleEUTRA_r16;

/* VarMeasIdleReport-r16 */
typedef struct VarMeasIdleReport_r16 {
	struct MeasResultIdleNR_r16	*measReportIdleNR_r16;	/* OPTIONAL */
	struct MeasResultIdleEUTRA_r16	*measReportIdleEUTRA_r16;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} VarMeasIdleReport_r16_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_VarMeasIdleReport_r16;

#ifdef __cplusplus
}
#endif

#endif	/* _VarMeasIdleReport_r16_H_ */
#include <asn_internal.h>
