/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-UE-Variables"
 * 	found in "nr-rrc-17.3.0.asn1"
 * 	`asn1c -no-gen-BER -no-gen-OER -no-gen-XER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -S /home/amd/wrk/asn1c_oai/skeletons/`
 */

#ifndef	_VarRLF_Report_r16_H_
#define	_VarRLF_Report_r16_H_


#include <asn_application.h>

/* Including external dependencies */
#include "RLF-Report-r16.h"
#include "PLMN-IdentityList2-r16.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* VarRLF-Report-r16 */
typedef struct VarRLF_Report_r16 {
	RLF_Report_r16_t	 rlf_Report_r16;
	PLMN_IdentityList2_r16_t	 plmn_IdentityList_r16;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} VarRLF_Report_r16_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_VarRLF_Report_r16;

#ifdef __cplusplus
}
#endif

#endif	/* _VarRLF_Report_r16_H_ */
#include <asn_internal.h>
